# Definitionen


- *Abweichungsrechteck*: @def-abweichungsrechteck[, s. S. \pageref{def-abweichungsrechteck}]{.content-visible when-format="titlepage-pdf"}
- *Ausprägung*: @def-auspraegung[, s. S. \pageref{def-auspraegung}]{.content-visible when-format="titlepage-pdf"}
- *Balkendiagramm*: @def-balken[, s. S. \pageref{def-balken}]{.content-visible when-format="titlepage-pdf"}
- *Beobachtungseinheit*: @def-beobeinheit[, s. S. \pageref{def-beobeinheit}]{.content-visible when-format="titlepage-pdf"}
- *Binäre Variable*: @def-binvar[, s. S. \pageref{def-binvar}]{.content-visible when-format="titlepage-pdf"}
- *Boxplot*: @def-boxplot[, s. S. \pageref{def-boxplot}]{.content-visible when-format="titlepage-pdf"}
- *Data-Dictionary*: @def-datadict[, s. S. \pageref{def-datadict}]{.content-visible when-format="titlepage-pdf"}
- *Dataframe*: @def-dataframe[, s. S. \pageref{def-dataframe}]{.content-visible when-format="titlepage-pdf"}
- *Daten*: @def-daten[, s. S. \pageref{def-daten}]{.content-visible when-format="titlepage-pdf"}
- *Datendiagramm*: @def-datendiagramm[, s. S. \pageref{def-datendiagramm}]{.content-visible when-format="titlepage-pdf"}
- *Datenjudo*: @def-datenjudo[, s. S. \pageref{def-datenjudo}]{.content-visible when-format="titlepage-pdf"}
- *Dezile*: @def-dezile[, s. S. \pageref{def-dezile}]{.content-visible when-format="titlepage-pdf"}
- *Dichtediagramm*: @def-dichtediagramm[, s. S. \pageref{def-dichtediagramm}]{.content-visible when-format="titlepage-pdf"}
- *Das einfache lineare Modell*: @def-einfache-lineare-modell[, s. S. \pageref{def-einfache-lineare-modell}]{.content-visible when-format="titlepage-pdf"}
- *Extremwert*: @def-extremwert[, s. S. \pageref{def-extremwert}]{.content-visible when-format="titlepage-pdf"}
- *Fehlerstreuung*: @def-fehlerstreung[, s. S. \pageref{def-fehlerstreung}]{.content-visible when-format="titlepage-pdf"}
- *Funktion*: @def-fun[, s. S. \pageref{def-fun}]{.content-visible when-format="titlepage-pdf"}
- *Gerade*: @def-gerade[, s. S. \pageref{def-gerade}]{.content-visible when-format="titlepage-pdf"}
- *Histogramm*: @def-histogramm[, s. S. \pageref{def-histogramm}]{.content-visible when-format="titlepage-pdf"}
- *Interaktionseffekt*: @def-interakt[, s. S. \pageref{def-interakt}]{.content-visible when-format="titlepage-pdf"}
- *Interquartilsabstand*: @def-iqr[, s. S. \pageref{def-iqr}]{.content-visible when-format="titlepage-pdf"}
- *Konfidenzintervall*: @def-konfidenzintervall[, s. S. \pageref{def-konfidenzintervall}]{.content-visible when-format="titlepage-pdf"}
- *Kovarianz*: @def-kov[, s. S. \pageref{def-kov}]{.content-visible when-format="titlepage-pdf"}
- *Lagemaß*: @def-lage[, s. S. \pageref{def-lage}]{.content-visible when-format="titlepage-pdf"}
- *Linearer Zusammenhang*: @def-lin-zshg[, s. S. \pageref{def-lin-zshg}]{.content-visible when-format="titlepage-pdf"}
- *Lineares Modell*: @def-lm[, s. S. \pageref{def-lm}]{.content-visible when-format="titlepage-pdf"}
- *Mittlere Absolutabweichung*: @def-mae[, s. S. \pageref{def-mae}]{.content-visible when-format="titlepage-pdf"}
- *Median*: @def-median[, s. S. \pageref{def-median}]{.content-visible when-format="titlepage-pdf"}
- *Modelle*: @def-modelle[, s. S. \pageref{def-modelle}]{.content-visible when-format="titlepage-pdf"}
- *Multiple Regression*: @def-mult-regr[, s. S. \pageref{def-mult-regr}]{.content-visible when-format="titlepage-pdf"}
- *Mittelwert*: @def-mw[, s. S. \pageref{def-mw}]{.content-visible when-format="titlepage-pdf"}
- *Normalverteilung*: @def-norm[, s. S. \pageref{def-norm}]{.content-visible when-format="titlepage-pdf"}
- *Entstehung einer Normalverteilung*: @def-normal-galton[, s. S. \pageref{def-normal-galton}]{.content-visible when-format="titlepage-pdf"}
- *Nullmodell (Punktmodell)*: @def-nullmodell[, s. S. \pageref{def-nullmodell}]{.content-visible when-format="titlepage-pdf"}
- *Pfeife*: @def-pipe[, s. S. \pageref{def-pipe}]{.content-visible when-format="titlepage-pdf"}
- *Punktmodell*: @def-punktmodell[, s. S. \pageref{def-punktmodell}]{.content-visible when-format="titlepage-pdf"}
- *Quantile*: @def-quantile[, s. S. \pageref{def-quantile}]{.content-visible when-format="titlepage-pdf"}
- *Quartile*: @def-quartile[, s. S. \pageref{def-quartile}]{.content-visible when-format="titlepage-pdf"}
- *Korrelationskoeffizient $r$*: @def-r[, s. S. \pageref{def-r}]{.content-visible when-format="titlepage-pdf"}
- *$R^2$-Quadrat*: @def-r2[, s. S. \pageref{def-r2}]{.content-visible when-format="titlepage-pdf"}
- *Spannweite*: @def-range[, s. S. \pageref{def-range}]{.content-visible when-format="titlepage-pdf"}
- *Reproduzierbarkeit*: @def-repro[, s. S. \pageref{def-repro}]{.content-visible when-format="titlepage-pdf"}
- *Residuum*: @def-residuum[, s. S. \pageref{def-residuum}]{.content-visible when-format="titlepage-pdf"}
- *Standardabweichung*: @def-sd[, s. S. \pageref{def-sd}]{.content-visible when-format="titlepage-pdf"}
- *Skalenniveau*: @def-skalenniveau[, s. S. \pageref{def-skalenniveau}]{.content-visible when-format="titlepage-pdf"}
- *Statistik*: @def-statistik[, s. S. \pageref{def-statistik}]{.content-visible when-format="titlepage-pdf"}
- *Streuungsmaße*: @def-streuungsmaße[, s. S. \pageref{def-streuungsmaße}]{.content-visible when-format="titlepage-pdf"}
- *Test-Sample*: @def-testsample[, s. S. \pageref{def-testsample}]{.content-visible when-format="titlepage-pdf"}
- *Tidy Data*: @def-tidy[, s. S. \pageref{def-tidy}]{.content-visible when-format="titlepage-pdf"}
- *Train-Sample*: @def-trainsample[, s. S. \pageref{def-trainsample}]{.content-visible when-format="titlepage-pdf"}
- *Variable*: @def-var[, s. S. \pageref{def-var}]{.content-visible when-format="titlepage-pdf"}
- *Varianz*: @def-var[, s. S. \pageref{def-var}]{.content-visible when-format="titlepage-pdf"}
- *Vektorielles Rechnen*: @def-veccalc[, s. S. \pageref{def-veccalc}]{.content-visible when-format="titlepage-pdf"}
- *Vektor*: @def-vektor[, s. S. \pageref{def-vektor}]{.content-visible when-format="titlepage-pdf"}
- *Verteilung*: @def-verteilung[, s. S. \pageref{def-verteilung}]{.content-visible when-format="titlepage-pdf"}
- *Wert*: @def-wert[, s. S. \pageref{def-wert}]{.content-visible when-format="titlepage-pdf"}
- *z-Werte*: @def-z-werte[, s. S. \pageref{def-z-werte}]{.content-visible when-format="titlepage-pdf"}
- *Zentrieren*: @def-zentrieren[, s. S. \pageref{def-zentrieren}]{.content-visible when-format="titlepage-pdf"}
