# Data-Dictionary für Mariokart {#sec-data-dict}

In diesem Datensatz werden Auktionen zum Videospiel *Wii Mario Kart* 
beim Online-Auktionshaus Ebay dargestellt. 
Die Daten wurden im Oktober 2009 gesammelt.
Es handelt sich um einen Dataframe mit 143 Beobachtungen (Auktionen) und 12 Spalten (Variablen).
Die Preise sind in US-Dollar angegeben.


Die Quelle des Datensatzes ist das R-Paket `openintro` [@openintro].

| Variable    	| Erklärung                                                                                                              	|
|-------------	|------------------------------------------------------------------------------------------------------------------------	|
| id          	| ID der Auktion                                                                                                         	|
| duration    	| Dauer der Auktion in Tagen                                                                                             	|
| n_bids      	| Anzahl der Gebote                                                                                                      	|
| cond        	| Zustand (new/used)                                                                                                     	|
| start_pr    	| Anfangspreis bei der Auktion                                                                                           	|
| ship_pr     	| Versangebühr                                                                                                           	|
| total_pr    	| Gesamtpreis (inkl. Versandgebühr)                                                                                      	|
| ship_sp     	| Versandmethode bzw. -geschwindigkeit                                                                                   	|
| seller_rate 	| Bewertung des Verkäufers; das ist die Differenz zwischen positiven und negativen Bewertungen                           	|
| stock_photo 	| Lag der Auktion ein "stock photo" bei? Wenn ein Foto in vielen Auktionen benutzt wurde, wird es "stock photo" genannt. 	|
| wheels      	| Anzahl der enthaltenen Wii-Räder.                                                                                      	|
| title       	| Name der Auktion                                                                                                       	|


Mit `help(mariokart)` wird die Hilfeseite zum Datensatz geöffnet (dazu muss das Paket `openintro` bereitgestellt sein).


