# Probeklausur


```{r}
#| include: false

library(exams2forms)
source("_common.R")
```


Siehe diese [Prüfungshinweise](https://hinweisbuch.netlify.app/030-hinweise-pruefung-klausur-frame) und alle weiteren Hinweise.





```{r def-exs-probeklausur}
#| echo: false





# exrs_probe <- c(
# #  "variation01.Rmd",
#   "Definition_Statistik.Rmd",
#   "Definition_Statistik.Rmd",
#   "Skalenniveau_Intervall.Rmd",
#   "Ziele_Statistik.Rmd",
#  # "variation02.Rmd",
#   "Skalenniveau_Ordinal.Rmd",
#   #"tidydata1.Rmd",
#   "Aufgaben_Statistik.Rmd",
#   "typ-fehler-r-02.rmd",
#   "typ-fehler-r-07.rmd",
#   #"typ-fehler-r-08-name-clash.Rmd",
#  "Logikprüfung_Anwendung.Rmd",
#   #"logikpruefung2.Rmd",
#   #"there-is-no-package.Rmd",
#   #"wertberechnen2.Rmd",
#   #"argumente.Rmd",
#   #"import-mtcars.Rmd",
#   "Zuweisung_Operator.Rmd",
#   #"wertpruefen.Rmd",
#   #"wrangle1.Rmd",
#   #"repro1-sessioninfo.Rmd",
#   "MW_Eigenschaft.Rmd",
#   #"wrangle3.Rmd",
#   #"wrangle4.Rmd",
#   #"wrangle5.Rmd",
#   #"wrangle7.Rmd",
#   #"wrangle9.Rmd",
#   #"wrangle10.Rmd",
#   "affairs-dplyr.Rmd",
#   "dplyr-uebersetzen.Rmd",
#   "haeufigkeit01.Rmd",
#   #"mariokart-mean1.Rmd",
#   "mariokart-mean2.Rmd",
#   #"mariokart-mean3.Rmd",
#   #"mariokart-mean4.Rmd",
#   #"mariokart-max1.Rmd",
#   "mariokart-max2.Rmd",
#   #"filter01.Rmd",
#   "summarise01.Rmd",
#   #"summarise02.Rmd",
#   "mutate01.Rmd",
#   #"boxhist.Rmd",
#   "max-corr1.Rmd",
#   #"max-corr2.Rmd",
#  # "histogramm-in-boxplot.Rmd",
#   #"diamonds-histogramm-vergleich2.Rmd",
#   "boxplot-aussagen.Rmd",
#   #"boxplots-de1a.Rmd",
#   #"movies-vis1.Rmd",
#   #"movies-vis2.Rmd",
#   #"vis-gapminder.Rmd",
#   #"diamonds-histogramm-vergleich.Rmd",
#   #"wozu-balkendiagramm.Rmd",
#   #"diamonds-histogram.Rmd",
#   "n-vars-diagram.Rmd",
#   #"kennwert-robust.Rmd",
#   "nasa01.Rmd",
#   #"schiefe1.Rmd",
#   #"summarise03.Rmd",
#   #"mariokart-sd2.Rmd",
#   "mariokart-sd3.Rmd",
#   "summarise04.Rmd",
#   #"summarise05.Rmd",
#   "vis-mariokart-variab.Rmd",
#   #"sd-vergleich.Rmd",
#   "streuung-histogramm.Rmd",
#   #"mariokart-sd1.Rmd",
#   #"summarise06.Rmd",
#   "mariokart-desk01.Rmd",
#   #"nasa02.Rmd",
#   #"mariokart-korr1.Rmd",
#   "mariokart-korr2.Rmd",
#   #"mariokart-korr3.Rmd",
#   #"mariokart-korr4.Rmd",
#   "korr01.Rmd"
#   #"korr02.Rmd"
#   #"aussagen-einfache-regr.Rmd",
#   #"interpret-koeff-lm.Rmd",
#   #"korr-als-regr.Rmd",
#   #"linearitaet1a.Rmd",
#   #"lm1.Rmd",
#   #"mtcars-regr01.Rmd",
#   #"nichtlineare-regr1.Rmd",
#   #"penguins-regr02.Rmd",
#   #"regression1.Rmd",
#   #"regression1b.Rmd",
#   #"regression3.Rmd",
#   #"regression4.Rmd",
#   #"regression5.Rmd",
#   #"regression6.Rmd",
#   #"ames-kaggle1.Rmd",
#   #"interpret-koeff.Rmd",
#   #"regression1a.Rmd",
#   #"lm-mario1.Rmd",
#   #"lm-mario2.Rmd",
#   #"lm-mario3.Rmd",
#   #"ausreisser1.Rmd",
#   #"mario-compare-models.Rmd"
# )
# 
# # Duplikate entfernen und alphabetisch sortieren (optional)
# #alle_quiz_rmds <- sort(unique(exrs_probe))



```


```{r def-exs-probe}
#| echo: false
exrs_probe <- c(
  "Aufgaben_Statistik.Rmd",
  "Anscombe_Logik.Rmd",
  "Count_Nominal.Rmd",
  "Datentypen_Coercion.Rmd",
  "Definition_Punktmodell.Rmd",
  "Dollar_Operator.Rmd",
  "Filter_Logik.Rmd",
  "Funktionsargumente_Defaults.Rmd",
  "Gruppen_Modell_Vorteil.Rmd",
#  "Interaktion.Rmd",
  "Korrelation_Richtung.Rmd",
  "Kovarianz_Skalierung.Rmd",
  "Lego_Prinzip_Logik.Rmd",
  "Logikprüfung_Anwendung.Rmd",
  "MAE_Berechnung.Rmd",
  "Mean_NA_Standard.Rmd",
 # "Modellvergleich_MAE.Rmd",
  "Mutate_Neu.Rmd",
  "NA_Handling_Transfer.Rmd",
  "Neg_Slope.Rmd",
  "Normal_Rechnen.Rmd",
#  "Null_vs_Lin.Rmd",
 # "Overfitting.Rmd",
  "Pipe_Vorteil.Rmd",
  "Plot_Wahl.Rmd",
  "Praxis_Datenjudo.Rmd",
  "Resid_Calc.Rmd",
  "Robuste_Streuung.Rmd",
  "SD_vs_Varianz.Rmd",
  "MW_Eigenschaft.Rmd",
  "Korrelation_NA_Handling.Rmd",
  "Achsen_Trick.Rmd",
  "Korrelation_Z_Logik.Rmd",
  "NA_Bedeutung.Rmd"

  #"SimpsonPara.Rmd",
  #"Variablenwahl.Rmd"
)

```


```{r quiz-probe, echo = FALSE, message = FALSE, results = "asis"}
exams2forms(exrs_probe, box = TRUE, check = TRUE, edir = "exs", sdir = "exs")
```



