---
output:
  html_document:
    css: webex.css
    includes:
      after_body: webex.js
---

# Quiz


```{r}
#| include: false

library(exams)
library(exams2forms)
```

## Rahmen

```{r def-exs-rahmen}
#| echo: false
exrs_rahmen <- 
list(
  "exs/Definition_Statistik.Rmd",
  "exs/Nutzen_Modelle.Rmd",
  "exs/PPDAC_Modell.Rmd",
  "exs/Residuum_Definition.Rmd",
  "exs/Skalenniveau_Intervall.Rmd",
  "exs/Skalenniveau_Ordinal.Rmd",
  "exs/Stichprobengroesse_Genauigkeit.Rmd",
  "exs/Tidy_Data.Rmd",
  "exs/UV_AV_Unterscheidung.Rmd",
  "exs/Ziele_Statistik.Rmd"
  )
```

```{r quiz-kap2, echo = FALSE, message = FALSE, results = "asis"}
exams2forms(exrs_rahmen, box = TRUE, check = TRUE)
```

## Daten einlesen


```{r exr-daten-einlesen}
#| include: false
exrs_einlesen <- 
list(
  "exs/Reproduzierbarkeit.Rmd",
  "exs/R_vs_RStudio.Rmd",
   "exs/Zuweisung_Operator.Rmd",
   "exs/NA_Bedeutung.Rmd",
   "exs/Vektor_Erstellung.Rmd",
   "exs/Mean_NA_Standard.Rmd",
    "exs/Funktionsargumente.Rmd",
   "exs/Logikprüfung_Gleichheit.Rmd",
    "exs/Definition_Dataframe.Rmd",
    "exs/Dollar_Operator.Rmd"
)
```




```{r quiz-kap3, echo = FALSE, message = FALSE, results = "asis"}
exams2forms(exrs_einlesen, box = TRUE, check = TRUE)
```


