# Aufbereiten





```{r libs}
#| include: false
library(tibble)
library(tidyverse)
# library(grid)
# library(gridExtra)
```

```{r}
#| include: false
theme_set(theme_minimal())
```



```{css, echo = FALSE}
.justify {
  text-align: justify !important
}

.centered {
  text-align-last: center;
}
```



## Lernsteuerung

### Standort im Lernpfad

Abb. @fig-ueberblick-aufbereiten zeigt den Standort dieses Kapitels im Lernpfad und gibt damit einen Überblick über das Thema dieses Kapitels im Kontext aller Kapitel.



```{mermaid}
%%| fig-cap: Überblick über den Inhalt und Verlauf des Buches
%%| label: fig-ueberblick-aufbereiten

flowchart LR
  subgraph M[Modellieren]
    direction TB
    M1[Punktmodelle] --> Vis[Verbildlichen]
    Vis --> U[Ungewissheit]
    U --> G[Geradenmodelle]
  end
  A[Fragen stellen] --> Auf[<font size=4>Aufbereiten]
  Auf --> M
  M --> D[Antworten diskutieren]
```


```{r}
#| echo: false
ggplot2::theme_set(theme_minimal())
```


### Lernziele


- Sie können ...



### Benötigte R-Paket

In diesem Kapitel benötigen Sie die folgenden R-Pakete.


```{r}
#| message: false
library(tidyverse)
```







s
