# Datenschutzhinweise


## Einleitung

Diese Datenschutzhinweise informieren Sie über die Art, den Umfang und den Zweck der Verarbeitung von personenbezogenen Daten (nachfolgend "Daten") im Rahmen der Nutzung dieser Webseite (nachfolgend "Webseite"), die auf GitHub gehostet wird.

### Verantwortliche Person

Prof. Dr. habil. Sebastian Sauer, Residenzstr. 10, 90522 Ansbach, sebastian.sauer@hs-ansbach.de

### Hosting durch GitHub

Unsere Webseite wird von GitHub Inc., 88 Colin P. Kelly Jr. St, San Francisco, CA 94107, USA ("GitHub") gehostet. GitHub verarbeitet in unserem Auftrag Daten von Webseitenbesuchern (z.B. IP-Adressen). Dies ist für den Betrieb der Webseite und die Bereitstellung von Inhalten erforderlich.
GitHub ist unter dem Privacy-Shield-Abkommen zertifiziert und bietet hierdurch eine Garantie, das europäische Datenschutzrecht einzuhalten (<https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active>).


Weitere Informationen zum Datenschutz bei GitHub finden Sie in der Datenschutzerklärung von GitHub: <https://docs.github.com/de/site-policy/privacy-policies/github-general-privacy-statement>

## Datenerhebung und -verarbeitung

### Server-Log-Dateien

Bei jedem Zugriff auf unsere Webseite erfasst GitHub automatisiert Daten und speichert diese in Server-Log-Dateien. Zu diesen Daten gehören:
IP-Adresse des zugreifenden Geräts
Datum und Uhrzeit des Zugriffs
Name und URL der abgerufenen Datei
Webseite, von der aus der Zugriff erfolgt (Referrer-URL) 
Verwendeter Browser und ggf. das Betriebssystem des zugreifenden Geräts 
Name des Access-Providers


Die Verarbeitung dieser Daten erfolgt, um die Funktionsfähigkeit der Webseite sicherzustellen, die Nutzung der Webseite zu analysieren und unser Angebot zu verbessern. Rechtsgrundlage für die Datenverarbeitung ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse). Unser berechtigtes Interesse liegt in den oben genannten Zwecken.

### Cookies

Unsere Webseite verwendet keine Cookies.

### Einbindung von Drittinhalten
Es können Inhalte von Drittanbietern wie Videos, Schriftarten oder Karten eingebunden sein. Beim Abruf dieser Inhalte wird Ihre IP-Adresse möglicherweise an den Drittanbieter übertragen. Für weitere Informationen konsultiere bitte die Datenschutzrichtlinien der jeweiligen Anbieter.

## Ihre Rechte

Sie habengegenüber uns folgende Rechte hinsichtlich der dich betreffenden personenbezogenen Daten: 
Recht auf Auskunft (Art. 15 DSGVO)
Recht auf Berichtigung (Art. 16 DSGVO)
Recht auf Löschung (Art. 17 DSGVO)
Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO) 
Recht auf Datenübertragbarkeit (Art. 20 DSGVO)
Recht auf Widerspruch gegen die Verarbeitung (Art. 21 DSGVO)

Sie haben zudem das Recht, sich bei einer Datenschutz-Aufsichtsbehörde über die Verarbeitung deiner personenbezogenen Daten durch uns zu beschweren.

## Anwendbare Rechtsgrundlagen

Nachstehend geben wir Ihnen eine Übersicht der rechtlichen Grundlagen der DSGVO, auf deren Basis personenbezogene Daten auf dieser Webseite verarbeitet werden. Bitte beachten Sie, dass neben den Regelungen der DSGVO auch nationale Datenschutzvorgaben in Ihrem oder unserem Land relevant sein können. Sofern in Einzelfällen spezifische Rechtsgrundlagen gelten, werden diese in der Datenschutzerklärung gesondert erwähnt.


### Vertragserfüllung und vorvertragliche Maßnahmen (Art. 6 Abs. 1 S. 1 lit. b) DSGVO)

Die Verarbeitung personenbezogener Daten ist erforderlich zur Erfüllung eines Vertrags, bei dem die betroffene Person Vertragspartei ist, oder zur Durchführung vorvertraglicher Maßnahmen, die auf Anfrage der betroffenen Person erfolgen.

### Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f) DSGVO)

Die Datenverarbeitung erfolgt zur Wahrung berechtigter Interessen des Verantwortlichen oder eines Dritten, sofern keine entgegenstehenden Interessen, Grundrechte oder Grundfreiheiten der betroffenen Person, die den Schutz ihrer personenbezogenen Daten erfordern, überwiegen.


### Nationale Datenschutzbestimmungen in Deutschland

Neben der DSGVO gelten in Deutschland nationale Datenschutzvorgaben, insbesondere das Bundesdatenschutzgesetz (BDSG). Das BDSG beinhaltet spezielle Regelungen zum Recht auf Auskunft, Löschung, Widerspruch, zur Verarbeitung besonderer Kategorien personenbezogener Daten, zur Verarbeitung für andere Zwecke sowie zur Datenübermittlung und zu automatisierten Einzelentscheidungen einschließlich Profiling. In bestimmten Fällen können auch Datenschutzgesetze der Bundesländer Anwendung finden.

### Hinweis auf die Geltung von DSGVO und Schweizer DSG

Diese Datenschutzhinweise berücksichtigen die Vorgaben sowohl der DSGVO als auch des Schweizer Datenschutzgesetzes (DSG). Zur besseren Verständlichkeit und zur Vermeidung wiederholter Begriffsdefinitionen werden die Begriffe der DSGVO verwendet. Begriffe wie „Verarbeitung“, „personenbezogene Daten“, „berechtigtes Interesse“ und „besondere Kategorien von Daten“ entsprechen inhaltlich den Begriffen „Bearbeitung“, „Personendaten“, „überwiegendes Interesse“ und „besonders schützenswerte Personendaten“ des Schweizer DSG. Die genaue Auslegung und Anwendung erfolgt jedoch gemäß den Vorgaben des Schweizer DSG.


## Sicherheitsmaßnahmen

Wir setzen angemessene technische und organisatorische Maßnahmen zum Schutz Ihrer Daten entsprechend den gesetzlichen Anforderungen um. Dabei berücksichtigen wir den aktuellen Stand der Technik, die Implementierungskosten, Art, Umfang, Umstände und Zweck der Verarbeitung sowie die Wahrscheinlichkeit und Schwere möglicher Risiken für die Rechte und Freiheiten betroffener Personen.

Zu den Schutzmaßnahmen gehören insbesondere: Sicherstellung der Vertraulichkeit, Integrität und Verfügbarkeit von Daten durch Kontrolle des Zugriffs auf die Daten und die Infrastruktur, der Eingaben, Weitergaben und Trennungen von Daten. Zudem haben wir Verfahren eingerichtet, um die Rechte betroffener Personen zu gewährleisten, Daten zu löschen und angemessen auf Bedrohungen zu reagieren. Bereits in der Entwicklung und Auswahl von Hard- und Software sowie Verfahren berücksichtigen wir Datenschutzprinzipien wie Datenschutz durch Technikgestaltung und datenschutzfreundliche Voreinstellungen.

Sicherung von Online-Verbindungen mit TLS-/SSL-Verschlüsselung (HTTPS)
Um die Datenübertragung über unsere Online-Dienste vor unbefugtem Zugriff zu schützen, nutzen wir die TLS-/SSL-Verschlüsselungstechnologie. Dies gewährleistet eine sichere Datenübertragung zwischen unserem Server und Ihrem Browser, erkennbar an der HTTPS-Kennung in der URL-Leiste.


### Internationale Datenübertragungen

Falls Datenverarbeitungen in Drittländern (außerhalb der EU und des EWR) stattfinden oder personenbezogene Daten an Dritte im Ausland übermittelt werden, erfolgt dies ausschließlich unter Einhaltung gesetzlicher Anforderungen. Sofern ein Angemessenheitsbeschluss der EU-Kommission für das betreffende Drittland vorliegt (Art. 45 DSGVO), gilt dieser als Grundlage der Übertragung. Falls kein Angemessenheitsbeschluss vorliegt, sichern Standardvertragsklauseln (Art. 46 Abs. 2 lit. c) DSGVO), eine ausdrückliche Einwilligung oder gesetzliche Erfordernisse die Übertragung ab (Art. 49 Abs. 1 DSGVO).

Weitere Informationen zu den Angemessenheitsbeschlüssen der EU-Kommission finden Sie auf dieser Seite. Die USA bieten mit dem sogenannten „Data Privacy Framework“ (DPF) eine Regelung zur Sicherstellung eines angemessenen Datenschutzniveaus, das durch die EU-Kommission am 10.07.2023 anerkannt wurde. Die Liste der zertifizierten Unternehmen und weitere Informationen finden Sie auf der Webseite des US-Handelsministeriums unter Data Privacy Framework.

Wir informieren Sie in unseren Datenschutzhinweisen, welche Drittanbieter unter diesem Rahmen zertifiziert sind.








## Kontakt

Für Anfragen zum Datenschutz können Sie sich an uns wenden:

Prof. Dr. habil. Sebastian Sauer

Residenzstr. 10, 90522 Ansbach

sebastian.sauer@hs-ansbach.de


## Änderung der Datenschutzhinweise

Wir behalten uns vor, diese Datenschutzhinweise jederzeit anzupassen, um sie an geänderte Rechtslagen oder bei Änderungen des Dienstes sowie der Datenverarbeitung anzupassen.

Stand: 15. November 2024
