```{mermaid}
%%| fig-cap: Überblick über den Inhalt und Verlauf des Buches
%%| label: fig-ueberblick
%%| out-width: "100%"

flowchart LR
  subgraph R[Rahmen]
    direction LR
    subgraph V[Vorbereiten]
      direction TB
      E[Einlesen] --> Um[Umformen]
    end
    subgraph M[Modellieren]
      direction TB
      M1[Punktmodelle] --> Vis[Verbildlichen]
      Vis --> U[Ungewissheit]
      U --> G[Geradenmodelle]
    end
    subgraph N[Nachbereiten]
      direction TB
      D[Diskutieren]
    end
  V --> M
  M --> N
  end
```




```{mermaid}
%%| fig-cap: Überblick über den Inhalt und Verlauf des Buches
%%| label: fig-ueberblick-fragen
%%| out-width: "100%"


flowchart LR
  subgraph R[<font size=5>**Rahmen**]
    direction LR
    subgraph V[Vorbereiten]
      direction TB
      E[Einlesen] --> Um[Umformen]
    end
    subgraph M[Modellieren]
      direction TB
      M1[Punktmodelle] --> Vis[Verbildlichen]
      Vis --> U[Ungewissheit]
      U --> G[Geradenmodelle]
    end
    subgraph N[Nachbereiten]
      direction TB
      D[Diskutieren]
    end
  V --> M
  M --> N
  end


```






```{mermaid}
%%| fig-cap: Überblick über den Inhalt und Verlauf des Buches
%%| label: fig-ueberblick-umformen
%%| fig-width: 1


flowchart LR
  subgraph R[Rahmen]
    direction LR
    subgraph V[Vorbereiten]
      direction TB
      E[Einlesen] --> Um[<font size=5>**Umformen**]
    end
    subgraph M[Modellieren]
      direction TB
      M1[Punktmodelle] --> Vis[Verbildlichen]
      Vis --> U[Ungewissheit]
      U --> G[Geradenmodelle]
    end
    subgraph N[Nachbereiten]
      direction TB
      D[Diskutieren]
    end
  V --> M
  M --> N
  end


```






```{mermaid}
%%| fig-cap: Überblick über den Inhalt und Verlauf des Buches
%%| label: fig-ueberblick-vis
%%| fig-width: 1


flowchart LR
  subgraph R[Rahmen]
    direction LR
    subgraph V[Vorbereiten]
      direction TB
      E[Einlesen] --> Um[Umformen]
    end
    subgraph M[Modellieren]
      direction TB
      M1[Punktmodelle] --> Vis[<font size=5>Verbildlichen]
      Vis --> U[Ungewissheit]
      U --> G[Geradenmodelle]
    end
    subgraph N[Nachbereiten]
      direction TB
      D[Diskutieren]
    end
  V --> M
  M --> N
  end
```






```{mermaid}
%%| fig-cap: Überblick über den Inhalt und Verlauf des Buches
%%| label: fig-ueberblick-r
%%| out-width: "100%"


flowchart LR
  subgraph R[Rahmen]
    direction LR
    subgraph V[Vorbereiten]
      direction TB
      E[<font size=5>**Einlesen**] --> Um[Umformen]
    end
    subgraph M[Modellieren]
      direction TB
      M1[Punktmodelle] --> Vis[Verbildlichen]
      Vis --> U[Ungewissheit]
      U --> G[Geradenmodelle]
    end
    subgraph N[Nachbereiten]
      direction TB
      D[Diskutieren]
    end
  V --> M
  M --> N
  end


```


