# Prüfung

## Prüfungleistung

### Hauptleistung

Die Prüfungsleistung besteht aus einer Projektarbeit im Form eines *Prognosewettbewerb*.

```{r hinweise, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Hinweise/Prognosewettbewerb/Hinweise-Pruefung-Prognosewettbewerb-child.Rmd"

childtext <- readLines(url)
cat(childtext, sep = "\n")
```


### Bonusleistung

Es gibt eine Bonusleistung.
Eine Bonusleistung ist eine Leistung, die ...

- optional ist; die Teilnahme ist freiwillig
- nur zur Verbesserung führen kann; Sie können sich nicht verschlechtern
- überschaubar ist; der Aufwand ist im Vergleich zur Hauptleistung gering
- zu höchstens einer "Drittelnotenstufen" Verbesserung führt bei Bestehen (z.B. 2.0 anstatt 2.3)

Die Bonusleistung besteht aus *wöchentlichen Übungsaufgaben*.

Pro Thema (Kurswoche) wird ein Übungsblock bereitgestellt.
Es müssen alle Übungsblöcke bestanden werden, um die Bonusleistung zu bestehen.
Pro Übungsblock liegt die Bestehensgrenze bei (mind.) 50% gelösten Aufgaben.

Die Übungsblöcke werden in Moodle bereitgestellt.


:::{.callout-important}
Der Übungsblock eines bestimmten Themas is nur während der Woche des Themas freigeschaltet.
Nach Verstreichen der Woche, in der ein bestimmtes Thema unterrichtet wird, 
ist es nicht mehr möglich, den Kursblock zu bearbeiten. 
Ein Bestehen der Bonusleistung ist damit nicht mehr möglich.
:::




## Wie kann ich mich auf die Prüfung vorbereiten?

### Lösen Sie die Aufgaben

Die Prüfung orientiert sich an den Aufgaben, die jeweils am Kapitelende gestellt sind.
Nutzen Sie also die Aufgaben am Kapitelende fortwährend, um sich auf die Prüfung vorzubereiten.

### Arbeiten Sie kontinuierlich mit

Nach meiner Erfahrung kann jede/r eine gute Note schreiben, man muss kein "Mathe-Crack" sein.
Stattdessen kommt es auf die Vorbereitung bzw. das Mitlernen an.

:::{.callout-important}
Kontinuierliches Mitlernen ist der Schlüssel zum Erfolg.
:::

### Hier sind ein paar Tipps für Prüfungserfolg

Ein paar Tipps für Prüfungserfolg:

- Jedes Kapitel vor- und nachbereiten
- Die Aufgaben am Kapitelende selber lösen
- Das Lernen mit der Unterricht synchronisieren, nicht erst kurz vor der Prüfung anfangen.
- Dem Dozenten Fragen stellen (im Unterricht und per Forum)
- Lerngruppen bilden
- Exzerpte schreiben
- Karteikarten nutzen, um sich selber abzufragen

### Ich brauche mehr Erklärung

Schauen Sie sich die Vidoes [dieser Playlist](https://youtube.com/playlist?list=PLRR4REmBgpIFQIReNf_ihRm5GYJSKh3WT) an.


## Probeprüfung

### Gibt es eine Art "Probeklausur"?


Ja, [hier](https://github.com/sebastiansauer/Lehre/tree/main/data/prognosewettbwerb-demo). In diesem Ordner liegen die Dokumente, die Sie für die echte Prüfung auch bekommen:

1. Train-Datensatz
2. Test-Datensatz
3. Hinweise zur vorherzusagenden Variablen


### Welche weiteren Hilfen gibt es?


[Hier finden Sie ein Beispiel für eine Prognose-Analyse](https://sebastiansauer.github.io/Lehre/Hinweise/Prognosewettbewerb/Beispiel-Vorhersagemodellierung2.html). Und [hier](https://sebastiansauer.github.io/Lehre/Hinweise/Prognosewettbewerb/Beispiele-Fehler-Prognosewettbewerb.html) sehen Sie Beispiele für typische Fehler bei einem Prognosewettbewerb.






### Lieblingsfehler

- *Rechtschreibfehler* Manchmal muss man genau hinschauen, und leicht vertippt man sich: So heißt der Datensatz vielleicht `tips` und die Spalte, um die es Ihnen geht `tip` (oder war es umgekehrt?). Oder die Spalte heißt `bill_length` aber Sie schreiben `bill_lenght`.
- *Datensatz nicht richtig importiert* Ob ein Datensatz richtig importiert ist, erkennen Sie daran, ob er im Reiter "Environment" angezeigt wird. Außerdem können Sie dort den Datensatz anklicken, um zu einer Tabellenansicht des Datensatzes zu gelangen. Dort können Sie erkennen, ob z.B. die Anzahl der Spalten korrekt ist (und nicht etwa nur eine) oder z.B. ob die Spaltennamen korrekt sind.
- *`data(datensatz)` ohne vorher das zugehörige R-Paket gestartet zu haben*: Mit `data(datensatz)` können Sie den Datensatz `datensatz` *nur* dann verfügbar machen, wenn das Paket, in dem `datensatz` "wohnt", mit `library(paketname)` gestartet worden ist. So "wohnt" z.B. `penguins` im Datensatz `palmerpenguins`. [Hier](https://datenwerk.netlify.app/post/pfad/pfad/) finden Sie eine Übung (und weitere Erklärung) zum Importieren von Daten in R am Beispiel des Datensatzes `penguins`.
- Verwenden einer *Funktion, ohne das zugehörige R-Paket* vorab gestartet zu haben.
- Das Laden *zu vieler R-Pakete*, die gar nicht benötigt werden, mit dem Ergebnis, dass es mehrere Funktionen des gleichen Namens gibt (z.B. `filter()`). Das führt dann zu Verwirrung, da dann z.B. nicht die Funktion `filter` aus `tidyverse` (`dplyr`) verwendet wird, wie Sie annehmen, sondern eine Funktion gleichen Namens aus einem anderen Paket, das Sie auch gestartet haben. Tipp: Starten Sie nur die Pakete, die Sie für die Aufgabe benötigen. Zumeist sind das immer die gleichen wenigen Pakete.


## Hinweise zu Scheinmängeln

Immer wieder kommt es vor, dass Studierende Beanstandungen zu einer Prüfung vorbringen. Teilweise sind diese gerechtfertigt, teilweise nicht. Im Folgenden sehen Sie eine Auswahl an *nicht* gerechtfertigten Beanstandungen, also nur scheinbaren Mängeln, keine wirklichen Mängel, in einer Prüfung.

-   "Das zu wählende Vorgehen war nicht 100% klar" -- Wenn Sie der Meinung sind, dass das zu wählende Vorgehen (zum Lösen der Aufgabe) nicht komplett klar ist, treffen Sie Annahmen und weisen Sie darauf hin, dass Sie Annahmen getroffen haben. Zum anderen halten Sie sich an das Vorgehen aus dem Unterricht (bzw. den Unterlagen und der Literatur, die im Unterricht verwendet wurde). Eine andere Situation läge vor, wenn die Aufgabe nicht lösbar ist ohne weitere Angaben lösbar ist("Ist ein Effekt bei n=100 signifikant?"). Im Falle einer nicht lösbaren Aufgabe liegt der Fehler beim Prüfer.

-   "Ich sollte einen Punkt (ein Komma) als Dezimaltrennzeichen verwenden, aber Moodle hat ein Komma (einen Punkt) verlangt!" -- Je nach Spracheinstellung in Moodle kann es sein, dass Moodle nur einen Punkt als Dezimaltrennzeichen bzw. ein Komma als Dezimaltrennzeichen verwendet. Moodle weist Sie aber darauf hin, wenn eine Zahl nicht als Zahl erkannt wird, und zwar wenn Sie zur nächsten Aufgabe geben. Sie können also ohne Probleme den Fehler korrigieren. Darüber hinaus ist bei den Prüfungshinweisen vorab auf diesen Punkt verwiesen.





