# Vorwort


**Freude an statistischer Modellierung?**

Dieses Buch führt in die Statistik ein; es soll Freude am Lernen bereiten und konzentriert sich auf ein Thema, statistische Modellierung mittels moderner Werkzeuge. Es wendet sich an Studierende ohne Vorkenntnisse in Statistik. Es gibt schon viele Statistikbücher auf dieser Welt, braucht es da noch eines? Kritische studentische Stimmen würden vielleicht anmerken, dass schon ein Statistikbuch eines zu viel wäre. Ja, es gibt viele Statistikbücher, aber (meines Wissens) keines in deutscher Sprache, dass Freude beim Lernen vermittelt, sich auf statistische Modellierung konzentriert und moderne Werkzeuge einsetzt. Freude am Lernen, beim Angstgegner Statistik, wie soll das gehen? Viele Verständnisschwierigkeiten rühren daher, dass die Lehrbücher kompliziert geschrieben sind. Solcher Schreibweise liegt wohl die Überlegung zugrunde, dass die Konzepte präzise und umfangreich erläutert sein müssen. Meiner Ansicht nach wird da das Ziel mit dem Weg verwechselt: Am Anfang darf eine Erklärung ruhig etwas grober und detailärmer sein, überblickt man die Materie einigermaßen, kann man sich mit den Details vertraut machen, was Präzision und Tiefe verlangt. Darüber hinaus verwendet das Buch eine lockere Sprache, das Leben ist schon ernst genug. Für einigen Komfort beim Lesen wurde gesorgt: Lernziele, Definitionen, Beispiele, Übungen, Hinweise, Fehlerquellen, Tipps, Literatur, Verweise und mehr wurden hervorgehoben. An Erklärbildern wurde nicht gespart. 

Der Inhalt des Buches ist ganz auf statistische Modellierung ausgerichtet. Das ist ein sperriger Begriff, aber er sagt nur, dass es darum geht, fachliche Fragen in statistisch greifbare Bausteine zu gießen. Ein Beispiel: Studentin Anna fragt sich, ob viel Lernen viel nützt (zum Bestehen einer Prüfung im Studium)? Student Bert meint, dass Lernzeit und Intelligenz zusammen den Prüfungserfolg bestimmen. Studentin Carla ist hingegen überzeugt, dass Lernen an sich nix bringt, sondern dass die Intelligenz allein für den Prüfungserfolg verantwortlich sei; aber Intelligenz führe zu Interesse am Thema und damit auch zu höherer Lernzeit. Damit haben wir drei, noch recht unpräzise wissenschaftliche Modelle. Die Statistik hat nun die Aufgabe, präzise Antworten zu liefern, wofür Zahlen hilfreich sind. Wenn Anna, Bert und Carla ihre Überlegungen fachlich präzisieren und dann in statistische Sprache übersetzen, können wir mit Antworten rechnen, manchmal sogar präzise. Was nicht heißt, dass diese Antworten immer richtig oder nützlich sind. Tja, das Leben ist nicht leicht. 

Mit Blick auf den Spagat zwischen Wissen und Können irrt das Buch (sein Autor) zugunsten der Seite des Könnens. Ich wollte lieber befähigen, spannende Probleme zu lösen, als tiefen theoretischen Einblick zu vermitteln. Meine Hoffnung ist, dass die Freude am Können beflügelt, sich im nächsten Schritt tiefer mit der Materie zu beschäftigen. Ist es nicht auch so im Alltag? Was Freude macht, wo sich Erfolge einstellen, dort arbeiten wir gerne weiter.

Da sich das Buch auf ein Thema, Modellierung, konzentriert, bleiben andere Themen außen vor, vor allem Inferenzstatistik. Vielleicht freut sich die eine oder der andere, von diesem Thema verschont zu sein. Ich denke, dass Modellierung für die Forschung und für die Praxis ein zentraler Gedanke ist. Für zwei große Themen erscheint mir dieses Buch zu eng. 



**Tipps für Studierende**

Liebe Studierende, das Lesen einer Schwimmfibel ist nur bedingt nützlich, wenn Sie Freischwimmer werden wollen. Es hilft nichts: Rein in die Fluten! Wenn das Wasser nicht tief ist, man jederzeit Pause machen kann und die Erfolge sich schnell einstellen, steht Ihrem Fortschritt beim Lernen nichts im Weg. Ich gebe zu, mein Vergleich ist nicht gerade subtil. Aber es ist so: Sie lernen durch Tun [@lovett_applying_2000]. Dieses Buch bietet dafür reichhaltige Gelegenheit. Nutzen Sie sie. Jedes Kapitel führt am Ende eine Reihe von Aufgaben auf, alle mit Lösungen. So können Sie Ihren Lernfortschritt testen. Als Dozent höre ich immer wieder, dass Studierende Angst vor R haben. Meine Erfahrung ist: Wenn Studierende wissen, was sie mit einem bestimmten statistischen Schritt erreichen wollen, ist der R-Code auch klar. Daher: V