---
exname: r-fehler2
extype: schoice
exsolution: 10000
exshuffle: no
categories:
- R
- '2023'
- schoice
date: '2023-03-23'
slug: Typ-Fehler-R-02
title: Typ-Fehler-R-02

---




```{r libs, include = FALSE}

library(tidyverse)
library(mosaic)
library(glue)
library(testthat)
```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```






Question
========

R gibt folgende Fehlermeldung aus:


`(Fehler in library(XXX): es gibt kein Paket namens 'XXX')`,


wobei für `XXX` ein Paketname wie `tidyverse` angeführt wird.

Wählen Sie die plausibelste Ursache aus!


Answerlist
----------


* Das Paket `XXX` ist nicht installiert auf dem aktuellen Rechner.
* Das Paket `XXX` ist nicht verfügbar genau für dieses Betriebssystem.
* Es existiert kein Paket mit Namen `XXX`.
* Das Paket `XXX` ist nicht geladen.
* Das Paket `XXX` ist defekt.


Solution
========

Das Paket `XXX` ist nicht installiert auf dem aktuellen Rechner.

Answerlist
----------


* Richtig.
* Falsch.
* Falsch.
* Falsch.
* Falsch.





Meta-information
================
exname: typ-fehler-r-02
extype: schoice
exsolution: 10000
exshuffle: TRUE
