---
extype: string
exsolution: x+Y
exname: r-fehler3
expoints: 1
date: '2023-03-23'
slug: Typ-Fehler-R-03
title: Typ-Fehler-R-03
categories: string

---



```{r libs, include = FALSE}

library(tidyverse)
library(mosaic)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```









# Aufgabe

Gegeben sei diese Syntax:


```{r echo = TRUE}
x <- 42
Y <- 1
```

Lässt man folgende Syntax laufen, so kommt eine Fehlermeldung:

```{r echo = TRUE, error = TRUE}
X + Y
```


Geben Sie die korrekte Syntax ein (zur Berechnung der Summe), die *nicht* zu einer Fehlermeldung führt!

Bitte verwenden Sie *keine* Leerzeichen bei Ihrer Eingabe.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

```{r eval = TRUE, echo = TRUE}
x+Y
```

```{r}
sol <- "x+Y"
```

Die Antwort lautet: ``r sol``.





---

Categories: 

string

