---
extype: string
exsolution: mean(c(1,2,3,4),na.rm=TRUE)
exname: r-fehler4
expoints: 1
categories:
- R
- '2023'
- string
date: '2023-03-23'
slug: Typ-Fehler-R-04
title: Typ-Fehler-R-04

---



```{r libs, include = FALSE}

library(tidyverse)
library(mosaic)

```


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "")
```









# Aufgabe

Gegeben sei diese Syntax, die einen Fehlermeldung ausgibt:


```{r echo = TRUE, error = TRUE}
mean(c(1,2,3,4), na.rm = TRUE)
```


Geben Sie die korrekte Syntax ein, die *nicht* zu einer Fehlermeldung führt!

Bitte verwenden Sie *keine* Leerzeichen bei Ihrer Eingabe.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

```{r eval = TRUE, echo = TRUE}
mean(c(1,2,3,4), na.rm = TRUE)
```

```{r}
sol <- "mean(c(1,2,3,4),na.rm=TRUE)"
```


Die Antwort lautet: ``r sol``.




---

Categories: 

- R
- '2023'
- string

