---
extype: string
exsolution: r sol
exname: r-fehler1
expoints: 1
categories:
- R
- '2023'
- string
date: '2023-03-23'
slug: Typ-Fehler-R-01
title: Typ-Fehler-R-01

---




```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
                      fig.asp = 0.618,
                      fig.width = 4,
                      fig.cap = "", 
                      fig.path = "",
                      echo = FALSE,
                      message = FALSE,
                      fig.show = "hold")
```








# Aufgabe

Korrigieren Sie den Fehler in der Syntax: 

```{r eval = FALSE, echo = TRUE, error = TRUE}
mean(x = c(1, 5, 10, 52)
```


Ändern Sie *nur* diejenigen Teile der Syntax, die zwingend geändert werden müssen, damit der Fehler korrigiert wird.

Geben Sie in der Lösung *keine* Leerzeichen ein.



</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

# Lösung

```{r eval = TRUE, echo = TRUE}
mean(x=c(1,5,10,52))
```

```{r}
sol <- "mean(x=c(1,5,10,52))"
```


Die Antwort lautet: ``r sol``.




---

Categories: 

- R
- '2023'
- string

