

<!-- ## Allgemeine Prüfungshinweise -->

    

### Grundsätzliches

Die folgenden Hinweise gelten *grundsätzlich*, 
d.h. *soweit nicht anders* in der jeweiligen Prüfung bzw. der jeweiligen Aufgabe angegeben.

Nichtbeachten von Prüfungshinweisen kann zu Punkteabzug oder Nichtbestehen führen.




### Wiederholungsprüfungen

1. Wenn Sie bei einer Prüfung durchgefallen sein sollten, so haben Sie grundsätzlich die Möglichkeit, die *Prüfung zu wiederholen*.
2. Denken Sie daran, sich *rechtzeitig* für Prüfungsleistungen *anzumelden*; beachten Sie die Fristen. Beim Zweit- bzw. Drittversuch gelten besondere Regeln und Fristen. Informieren Sie sich umfassend.
3. Die *Termine* für die *Wiederholungsprüfungen* werden stets zusammen/zeitgleich mit denen der regulären Prüfungen bekannt gegeben. 
3. Relevanter Stoff und formale Bedingungen (wie Prüfungsform) sind *grundsätzlich identisch zur letzten abgehaltenen Prüfung des Moduls* (d.h. sofern nicht anders angegeben). Daher sind Wiederholungsprüfungen vom Anspruch vergleichbar wie die reguläre Klausur. Die Prüfungen sollen möglichst gleich vom Anspruch sein, um Fairness zu gewährleisten.
3. Beachten Sie immer die *Hinweise*, die für die Wiederholungsprüfung angegeben sind. Im Einzelfall keine eine Wiederholungsprüfung von der vorherigen Prüfung stärker abweichen. Es gelten immer die Regeln, die dis Dozenti bei der jeweiligen Wiederholungsprüfung veröffentlicht hat.
2.  Wird ein *Modul im laufenden Semester* angeboten, so gibt es keine Wiederholungsprüfung. Stattdessen können Sie ggf. an der regulären Klausur des Moduls teilnehmen. Es gilt der aktuelle Stoff bzw. die aktuellen formalen Bedingungen. Es ist möglich, dass der Stoff sich dann substanziell ändert; meist halten sich die Änderungen (im Stoff) aber in Rahmen.
3. Wird ein Modul im laufenden Semester nicht angeboten, gibt es eine *Wiederholungsprüfung.* 
2.  Sprechen Sie die *Moduldozentis an für Details zur Prüfung* (bzw. lesen Sie vorab auf jeweiligen Modulseite in Moodle nach).
2.  Manchmal fragen Studentis nach einer *Empfehlung*, ob es besser ist, eine Prüfung zu verschieben, wenn man sich nicht ausreichend vorbereiten konnte. Es ist schwer, eine Empfehlung pauschal abzugeben; es kommt auf den Einzelfall an. Grundsätzlich rate ich aber dazu, Prüfungen nicht zu verschieben: Schließlich könnte in einem folgenden Semester wieder ein unvorhergesehenes Problem auftreten.
2.  Bei Fragen zum *Prüfungsrecht* sprechen Sie bitte die *Studienberatung* an.
3. Handelt es sich bei der Prüfung um eine Projektarbeit (oder vergleichbare Leistung), so ist als Wiederholungsprüfung ein *neues Thema* zu bearbeiten. Das "alte" (nicht eingereichte) Thema darf *nicht* weitergeführt werden, da sonst die Bearbeitungszeit unzulässigerweise zu lange wäre (z.B. ein Jahr).








### Prüfungsrelevanter Stoff

*Prüfungsrelevanter* Stoff ist alles, was im Unterricht behandelt wurde, sofern es nicht explizit (und schriftlich) als "nicht prüfungsrelevant" gekennzeichnet ist.
Insbesondere ist der komplette Inhalt des Skripts und sonstiger vom Dozenten eingestellter Unterlagen prüfungsrelevant (sofern nicht in Teilen anderweitig gekennzeichnet).
Dazu zählen auch Hinweise auf zu lesende Literatur, aber nicht sonstige Literatur im Literaturverzeichnis.




### Teilnahmebedingungen

1. Eine *Prüfungsleistung* darf nur *eingereicht* werden, wenn Sie (erfolgreich) zur Prüfung *angemeldet* sind. Eine abgegebene/hochgeladene Arbeit, die nicht erfolgreich angemeldet ist, gilt nicht als erfolgreich eingereicht.
1.  Die Prüfung ist selbständig, also alleine nur durch Sie (Prüfling), *ohne Hilfe Dritter*, zu absolvieren.
2.  Die *Bearbeitungszeiten* der Prüfung sind einzuhalten.
2.  Es dürfen nur die explizit als zulässig gekennzeichneten *Hilfsmittel* verwendet werden.
2.  Die *zulässigen* Hilfsmittel sind: Notizpapier, Stifte, Taschenrechner, Vorlesungsfolien, Skripte, eigene Notizen, Bücher sowie Quellen aus dem Internet.
2.  Die Übernahme von Inhalten Dritter muss also solche gekennzeichnet (*zitiert*) werden. 
2.  Eine wörtliche Übernahme ("*copy-paste*") von Inhalten Dritter (etwa aus einer Quelle aus dem Internet) ist unzulässig.
2.  Bei *technischen Problemen* ist sofort der Prüfer bzw. die Prüferin zu verständigen und das technische Problem zu dokumentieren. Aus der Dokumentation muss der Fehler erkenntlich sein. 
2.  Es ist *untersagt*, die *Prüfung* bzw. Teile daraus (z.B. Prüfungsfragen) zu speichern oder *weiterzugeben.*
2.  Im Übrigen gelten die allgemeinen *Prüfungsregeln*.
2.  Es darf *nicht* mit anderen Personen, insbesondere nicht Prüflingen, *kommuniziert* werden während der Prüfung. Dies gilt auch für den Fall von (vermeintlichen) technischen Problemen. Kontaktieren Sie den Prüfer, wenn Sie meinen, es liege ein technisches Problem vor.



###  Organisatorische Hinweise


#### Allgemeines

1.  Etwaige weitere *Stoffeingrenzungen* werden schriftlich bekannt gemacht (auf der Modulseite). Besondere Schwerpunkte gibt es nicht.
2.  Soweit bestimmte Inhalte nicht explizit ausgeschlossen sind, sind alle Inhalte, die im Rahmen des Moduls bearbeitet wurden, *prüfungsrelevant.*
2.  Im Übrigen gelten die Hinweise der *offiziellen Regularien* wie SPO, auf dem Modulsteckbrief und der APO. Bitte kontaktieren Sie die Studienberatung für formale oder rechtliche Fragen. 
2.  Während der Prüfung werden nur Fragen beantwortet, die für die Bearbeitung zwingend nötig sind (etwa bei technischen Problemen).
2.  *Keine Vorab-Korrektur*: Es werden keine Fragen der Art "Ist diese Aufgabe klar formuliert?" beantwortet während der Prüfung. Sollten Sie der Meinung sein, eine Frage ist unklar formuliert oder fehlerhaft, so notieren Sie dies bitte (z.B. im Kommentarfeld der Prüfung=. Der Prüfer untersucht im Nachgang die Angelegenheit. Stellt sich eine Frage als fehlerhaft oder unklar formuliert heraus, so wird sie von der Beurteilung herausgenommen.
2.  Eine Teilnahme an der Prüfung ist nur möglich, wenn Sie den *Teilnahmebedingungen* der Prüfung zustimmen. Nehmen Sie an der Prüfung teil, so heißt das, dass Sie die Teilnahmebedingungen akzeptiert haben. Falls Sie Fragen oder Hinweise haben, können Sie sich jederzeit an die Prüfperson wenden.
2.  Die *Aufgabenstellung* der Prüfung wird ggf. nur *während des Prüfungszeitraumes* angezeigt.
2.  Beachten Sie eine etwaige *Gruppeneinteilung* (zu welcher Gruppe Sie zugeteilt sind). 
2.  Beachten Sie die exakte *Prüfungsuhrzeit* (Beginn, Ende). 
2.  Prüfungszeitraum, Aufgabenstellung und sonstige Materialien können variieren zwischen den Prüflingen etwa aufgrund von *Gruppeneinteilungen* oder *Nachteilsausgleich.*
2.  Die zusätzliche Bearbeitungszeit bei Studentis mit *Nachteilsausgleich* ist in der Aufgabenstellung bzw. der Prüfung in Moodle hinterlegt. Die Zeit wird automatisch um den jeweiligen Faktor bzw. Wert erhöht.




#### Technische Probleme während der Prüfung

Im Falle eines technischen Problems auf Seiten der *Prüfungsinfrastruktur* ist sofort der Prüfer zu informieren. Ein Beispiel für so ein Problem wäre etwa der Ausfall von Moodle. Der technische Fehler ist zu dokumentieren (z.B. Screenshot) und die Dokumentation ist einzureichen. Bitte beachten Sie, dass der Prüfer bzw. die Hochschule keine Gewähr übernimmt für Probleme mit Ihrer eigenen Ausstattung. 



#### Zeitrahmen der Prüfung

Die Prüfung beginnt und endet zu einem festen Zeitpunkt. Sie sind selber verantwortlich, die Prüfung zur korrekten Zeit zu beginnen und zu beenden (einzureichen). Verspätete Abgaben werden u.U. als nicht bestanden gewertet. Die Dauer der Prüfung wird Ihnen von Ihrer Prüferin bzw. Ihrem Prüfer bekannt gegeben. 













### Anspruch

In die Notengebung fließt folgende Konzeption zum Anspruch an die Prüfungsarbeit ein:


1. *Sehr gute Leistung*: Der Stoff aus dem Unterricht wird in sehr breitem Umfang und sehr hoher Tiefe in höchstem Maße korrekt angewandt. Die Stärken und Schwächen des gewählten Vorgehens werden ausgiebig und korrekt reflektiert.

2. *Ausreichende Leistung*: Wesentliche Teile des Stoffes aus dem Unterricht werden in einiger Breite wenn auch mit geringer Tiefe überwiegend korrekt angewandt. Eine Reflektion des Vorgehens ist in Ansätzen zu erkennen.


Es wird *kein unbehandelter Stoff* vorausgesetzt für (sehr gutes) Absolvieren der Prüfung.
Als "behandelter" Stoff gelten alle Inhalte, die als *prüfungsrelevant* gekennzeichnet sind.




### Plagiate

Lassen Sie äußerste Vorsicht walten, dass sich keine Plagiate in Ihrer Abschlussarbeit finden. 
Finden sich Plagiate, so wird die Arbeit mit "nicht bestanden" beurteilet. 
Eine Leistung als die eigene auszugeben, die aber gar nicht die eigene ist, ist unlauter. 
Bitte bedenken Sie auch, dass Verteidigungen wie "war keine Absicht, hab nicht aufgepasst" nicht ausreichen: 
*Sie* sind für die Qualität und Redlichkeit Ihrer Arbeit verantwortlich. 
In Ihrer Verantwortung liegt entsprechend die notwendige Sorgfalt, Plagiate zu vermeiden. 
Auch die Replik "Mein Literaturprogramm oder Word muss hier einen Fehler gemacht haben" wird nicht gelten gelassen werden. 
Hier gilt wieder: Sie sind für die Qualität und Redlichkeit Ihrer Abschlussarbeit verantwortlich; 
die Verantwortung ist nicht an eine Maschine delegierbar. 
Beachten Sie auch, dass sowohl direkte als auch indirekte Zitate als solche kenntlich gemacht sein müssen.


Ihre Prüfungsarbeiten können auf Plagiate hin untersucht werden, auch unter Einsat von maschinellen Methoden oder KI-basierten Methoden (z.B. mit [dieser Methode](https://pubmed.ncbi.nlm.nih.gov/37426542/)). 
Dabei können die Daten auch an Drittanbieter (z.B. Anbieter von Software zur Plagiatserkennung).

Bitte beachten: Angenommen in den Projektarbeiten von Studenti A und B werden (substanzielle) Überlappungen gefunden. 
In dem Fall ist davon auszugehen, dass *beide* Studentis getäuscht haben: eine/r hat abgeschrieben, der/die andere hat die eigene Arbeit dafür bereitgestellt. 
Daher wird in diesem Fall u.U.  bei beiden Studentis der Plagiatsfall festgestellt und geahndet (z.B. mit "nicht  bestanden" bewertet). 
Die genauen Konsequenzen legt die Prüfungskommission im Einzelfall fest.

Lassen Sie es auf keinen Fall soweit kommen: 
Schreiben Sie nicht ab und lassen Sie niemanden von Ihrer Arbeit abschreiben. 

Eine faire Prüfung heißt: *Gleiche Chancen für alle*, und *gute Leistung wird belohnt*, Täuschung nicht.



### Widerspruch einlegen


Falls Sie der Meinung sind, der Gutachter hätte Ihre Arbeit nicht korrekt beurteilt, 
haben Sie folgende Möglichkeiten zum Widerspruch.
Bitte halten Sie folgende Reihenfolge ein:



1. *Prüfungseinsicht*: Schauen Sie sich die Aufgabe und Bewertung genau an. 
2. Gespräch mit *Gutachter*: Sprechen Sie mit Isis Gutachti, vielleicht kann man in einem Gespräch etwaige Missverständnisse klären.
3. *Widerspruch* einlegen: Sie können formlos beim Studierendenservice Widerspruch einlegen (bis 4 Wochen nach Notenbekanntgabe). Ihr Widerspruch wird dann in der Fakultät geprüft. Studierendenservice lässt sich die Unterlagen des Prüfers geben und leitet den Widerspruch und die Prüfung an den Prüfungsausschuss weiter. Dieser entscheidet über die Note. Nur im Zweifelsfall kommt hier noch der Zweitprüfer ins Spiel.
4. Der *Rechtsweg* steht Ihnen offen.


Folgenden Kritikpunkte von Studentis führen i.d.R. *nicht* zu einer Änderung der Note:

- "Das ist zu streng benotet."
- "Da war kein konstruktives Feedback dabei."
- "Der Gutachter hat nicht geschrieben, wie man den Satz/das Argument/die Seminararbeit besser formuliert hätte."
- "Die Note passt nicht zu den Hinweisen der Gutachterin."
- "Die Gutachterin konnte mir die Note nicht verständlich machen."
- "Eine andere Studentin hat das aber so ähnlich geschrieben wie ich, und ihre Arbeit wurde besser benotet" - die Vergleichbarkeit von Seminararbeiten ist komplex, die Gesamtnote setzt sich aus vielen Aspekten zusammen, so dass man anhand eines einzelnen Aspekts nicht die Vergleichbarkeit der Noten beurteilen kann.
- "Die Aufgaben waren zu schwierig."
- "Ich bin mit der Note nicht zufrieden. Ich hätte mir was Besseres erhofft."
- "Ich habe nichts aus dem Gutachten gelernt."
- "Da war kaum Negatives im Gutachten."


Folgenden Kritikpunkte von Studentis haben *Aussicht* auf eine *Änderung* der Note:

- Der Gutachter hat sich *verzählt* (oder Punkte übersehen): Sie haben tatsächlich 43 Punkte, aber er hat nur 42 Punkte gezählt.
- Die Gutachterin hat einen Teil der *Prüfungsleistung übersehen* (vielleicht war ein Teil des Textes in einem Anhang, der in einer separaten Datei beigefügt war, die die Gutachterin nicht gesehen hat).
- Die Aufgabenstellung war *falsch* ("Was ist der Logarithmus von -1?").
- Die Aufgabenstellung war *missverständlich* ("Erläutern Sie den Hintergrund: 'Islamistische Selbstmordattentäter wollen als Mehrtürer sterben.'")


### Tipps

- Legen Sie regelmäßig *Sicherheitskopien* Ihrer Projektarbeit an (ggf. auf einem anderen Datenträger).
- Achten Sie darauf, dass Sie *nicht mit den Versionen durcheinander* kommen, in welcher Datei der aktuelle Stand Ihrer Projektarbeit liegt.
- Lesen Sie die *Hinweise* sorgfältig durch.
- Teilen Sie sich die *Zeit* entsprechend ein.


