
<!-- Hinweise zum Unterricht -->




### Sicherheitsunterweisung


- Der Dozent weist auf Fluchtwege und auf die Sammelstelle hin (abhängig vom Seminarraum).
- Flucht- und Rettungspläne hängen im Gebäude aus; bitte betrachten Sie sie sorgfältig. Prägen Sie sich die Rettungswege, den Ort der Sammelstelle sowie von Feuerlöschern und Brandmeldeeinrichtungen gut ein.
- Bei Alarm: Ruhe bewahren. Der Dozent weist an, den Raum sofort zu verlassen und geordnet über den kürzesten Weg zur Sammelstelle zu gehen. Tun Sie das.
- Prüfen Sie, ob niemand zurückgelassen ist (z. B. auf der Toilette).
- Fluchtwege (z. B. Fluren und Treppen) dürfen nicht versperrt sein.
- Notausgänge müssen ausgeschildert und frei zugänglich sein.
- Aufzüge dürfen im Brandfall nicht verwendet werden. Lebensgefahr!
- Im Brandfall sind Fenster und Türen zu schließen (aber nicht zu verriegeln!).
- Hilflose Personen sind mitzunehmen.
- Brände sind zu bekämpfen, aber die sichere Evakuierung hat Vorrang.
- Bei Bränden ist sofort die Feuerwehr zu alarmieren.
- Bei einem Hupton ist das Gebäude sofort zu verlassen und die Sammelstelle aufzusuchen. Brandschutztüren sind stets geschlossen zu halten.
- Prägen Sie sich die Position von Feuerlöschern und Erste-Hilfe-Material gut ein.



### Organisatorisches

- Bitte laden Sie sich rechtzeitig die Materialien herunter.
- Beachten Sie die Vorbereitungshinweise zur ersten Unterrichtsstunde und für die einzelnen Termine.
- Ein Foliensatz kann kein Lehrbuch ersetzen; falls Sie bei einem Termin gefehlt haben oder Ihre Aufzeichnung lückenhaft ist, lesen Sie bitte in der Literatur nach oder bitten Sie eine/n Kommiliton/in um Hilfe. 
- Beachten Sie die Hinweise der Hochschule (s. Moodle) wie die Orientierungshilfe, die Klausur- und Studiengangsordnungen. Dort finden Sie verbindliche Hinweise zu vielen organisatorischen Fragen.
- Bitte prüfen Sie jetzt schon und in regelmäßigen Abständen die Modulseite auf neue Materialien. 
- Nachdem eine Unterrichtseinheit abgeschlossen ist, ändert der Dozent grundsätzlich nichts mehr an den Materialien (in Ausnahmefällen wie etwa der Korrektur eines Fehler informiert der Dozent schriftlich).
- Es können sich Aktualisierungen des Unterrichtsmaterials ergeben. Bitte prüfen Sie regelmäßig, ob neues Material eingestellt ist. Nachdem der Unterricht stattgefunden hat, wird das Material aber nicht mehr geändert, so dass Sie Sicherheit für das Lernen haben.


### Präsenzunterricht

- Beachten Sie aktuell geltenden Hygienevorschriften.
- Bitte meiden Sie datenhungrige Applikationen wie das Streamen von Filmen – Sie behindern den Unterricht und verärgern damit andere Studierende (in diesem oder anderen Kursen).
- Bitte bringen Sie einen Computer (mit Internetanschluss) in alle Präsenztermine mit. Bringen Sie ggf. Ersatzbatterien und/oder Verlängerungskabel mit - leider sind nicht überall ausreichend Steckdosen vorhanden.


### Rechtliche Hinweise

- Dieser Kurs ist lizensiert unter der [MIT Lizenz](https://github.com/sebastiansauer/bayes-start/blob/main/LICENSE). Das ist eine permissive Lizenz, die erlaubt, dass Sie diesen Kurs frei verwenden können. Sie haben (nur) die Verpflichtung, zu zitieren und auf die Lizenzart hinzuweisen.
- Mitarbeit oder Verbesserungsvorschläge: am besten als Github Issue auf der Github-Seite dieses Projekts einstellen.
- Für die Inhalte von Links kann keine Haftung übernommen werden.
- Aus Datenschutzgründen dürfen Teilnehmis den Unterricht (Video, Ton, sonstige) nicht aufnehmen.


### Datenschutz 

- Einige Teile des Unterrichts werden u.U. aufgenommen. 
- Die Aufnahme erfolgt nur nach vorheriger Information durch den Dozenten. 
- Bei den Bild-Aufnahmen wird nur der Bildschirm des Dozenten aufgenommen; außerdem wird der Ton aufgenommen. 
- Bitte verzichten Sie daher während der Aufnahme auf Zoom-Reaktionen wie Hand heben, da diese u.U. mit Ihrem Namen auf dem Bildschirm des Dozenten und damit auf der Aufnahme zu sehen sind. 
- Während einer Aufnahme dürfen aus Datenschutzgründen keine Wortbeiträge zu hören sein, die Personen identifizieren. 
- Bitte verzichten Sie während der Aufnahme daher auf Wortbeiträge. - Der Dozent informiert umgehend, wenn er die Aufnahme beendet. 
- Die Aufnahmen werden im Internet (z.B. YouTube) frei veröffentlicht. Solche offenen Beiträge im Internet können u.U. in Zukunft nicht kontrolliert werden, insbesondere können sie unkontrolliert verbreitet und kommentiert werden. 
- Der Dozent hat u.U. keinen Einfluss auf Verbreitung, Kommentare oder sonstige Weiterverwendung. 
- Alle Rechte an den Aufnahmen liegen beim Dozenten. 
- Aufnahmen des Unterrichts durch die Studentis sind nicht erlaubt.


### IT

- Sie benötigen einen Computer für diesen Kurs. Ein Laptop ist ideal (ein günstiges Modell ist vollkommen ausreichend); ein Tablett ist nicht ideal, reicht aber zur Not, wenn Sie eine Tastatur für das Gerät haben.
- [Bereiten Sie bitte R und seine Freunden vor ](https://data-se.netlify.app/2021/11/30/installation-von-r-und-seiner-freunde/) vor der ersten Unterrichtsstunde. Sie können entweder R auf Ihrem Computer installieren oder den Cloud-Dienst *RStudio Cloud* nutzen. 
- Bitte beachten Sie die Installationshinweise für Software und stellen Sie sicher, dass die Software vor Beginn des ersten Termins einsatzbereit ist.
- Sorgen Sie dafür, dass Sie in jeder Stunde über eine gute Internetverbindung verfügen.
- Bitte stellen Sie sicher, dass Sie Zugriff auf Moodle, Zoom und weitere Dienste haben, die wir im Unterricht nutzen (Passwörter dabei haben etc.).
- Kontaktieren Sie die IT-Abteilung bei technischen Probleme.
- Für Präsenztermine: Bitte bringen Sie folgende IT-Geräte in jede Stunde mit: Laptop mit Stromkabel, Smartphone oder Tablett, Kopfhörer inkl. Mikrofon.
- Für Präsenztermine: Ein langer Uni-Tag zehrt an der Batterie; nicht nur an Ihrer, sondern auch in Ihrem Laptop und Smartphone. Ggf. kann eine Zusatzbatterie (Akku-Pack) hilfreich sein.
 Bei schlechter WLAN-Verbindung kann ein Hotspot über das Handy eine Lösung sein.
- Bitte lesen Sie auch die Hinweise zur Software, die wir in diesem Modul benötigen.
- Stellen Sie sicher, dass Sie die jeweils aktuelle Version für die in diesem Kurs verwendete Software verwenden (z.B. bei Zoom gibt es viele Aktualisierungen).
- Updaten Sie ggf. R, RStudio und Ihre R-Pakete.



### Ich brauche Hilfe. Was soll ich tun?

- Versuchen Sie erst selber, das Problem zu lösen. Manchmal hilft etwas Abstand (Pause, drüber schlafen), um ein Problem klarer zu sehen (oder es als nicht mehr so wichtig zu sehen).
- Fragen Sie Kommilitonis.
- Recherchen Sie (online) nach einer Lösung.
- Posten Sie das Problem im Forum oder einem Online-Forum. Wichtig: Stellen Sie Ihrem Post ein [Erbie](https://data-se.netlify.app/2022/01/31/erbie-einfache-reproduzierbare-beispiele-ihres-problems-mit-r-syntax/) bei.
- Besuchen Sie die Sprechstunde des Dozenten.
- Schreiben Sie möglichst keine Email, sondern posten Sie Ihre Frage im Forum o.Ä., da die meisten Fragen für Ihre Kommilitonis auch nützlich sein können (eine Ausnahme sind natürlich individuelle, persönliche Angelegenheiten, die nicht den Stoff betreffen).



### Videokonferenzen


- Ihr Dozent informiert Sie, ob Videokonferenzen in diesem Modul angeboten werden.
- Für Videokonferenzen/Webinare in diesem Modul wird die Software Zoom verwendet.
 Zur Einwahl benötigen Sie eine Zoom-Meeting-ID bzw. die dazu gehörige URL (Link); außerdem benötigen Sie ggf. ein zugehöriges Passwort. Diese Informationen werden Ihnen vom Dozenten zugestellt-.
- Für die Teilnahme an der Videokonferenz können Sie einen internetfähigen Rechner oder Tablet/Smartphone verwenden. Alternativ können Sie den Zoom-Client auf Ihrem Computer installieren (die Installation auf dem Rechner ist zu empfehlen).
- Ein paar Minuten vor Unterrichtsbeginn da sein, hilft beim Ankommen und um etwaige technische Probleme auszuräumen. 
- -Wenn jede(r) Hintergrundgeräusche vermeidet (auch die Tastatur kann ziemlich laute Geräusche verursachen), verstehen wir uns alle gut. 
- Das Mikro auszuschalten, wenn man gerade nichts sagen möchte, gibt Freiheit, doch nicht ganz leise zu sein, ohne die anderen zu stören. - Ein Headset ist hilfreich, um Rückkopplungsgeräusche (Echo) zu vermeiden. 
- Eine einigermaßen schnelle Internetverbindung ist nötig.
- Ich empfehle, eine Webcam anzuschließen (bzw. freigeben), so dass wir uns sehen können. Das ist der Qualität des Unterrichts zuträglich.
- Hilfe zu Zoom findet sich hier: https://support.zoom.us/hc/de.
- Zu bestimmten Seiten kann der Dienst (Zoom) überlastet sein, so dass das Webinar nur eingeschränkt oder nicht möglich ist. In diesem Fall erstellt der Dozent ein Video und stellt es im Nachgang über Moodle zur Verfügung.
- Die Datenschutzhinweise von Zoom finden Sie [hier.](https://zoom.us/docs/en-us/privacy-and-security.html)
- Prüfen Sie regelmäßig, ob Ihr Zoom-Client aktuell ist (sonst updaten).
- Aus Gründen der Sicherheit der Teilnehmis kann der Dozent anonyme Teilnahme an Videokonferenzen untersagen.
- Der Chat sollte nur für Themen des Unterrichts verwendet werden (nicht für private Themen).
- Aus Sicherheitsgründen kann eine Zoom-Konferenz auf Ihre "offizielle" E-Mail-Adresse (der Hochschule) begrenzt sein. Mit einer anderen, potenziell anonymen E-Mail-Adresse, können Sie also u.U. nicht teilnehmen.


### Streaming

In einigen Kursen wird Präsenzunterricht plus Streaming angeboten.
In diesem Fall gelten folgende Hinweise:

- Wenn die Teilnehmerzahl am Kurs geringer ist als die Raumkapazität (z.B. weniger als 80 Teilnehmis), so haben Sie stets freie Wahl, ob Sie in Präsenz beiwohnen oder den Unterricht online verfolgen. 
- Übersteigt die Teilnehmerzahl am Kurs die Raumkapazität bis zum Doppelten (z.B. 160 Teilnehmis bei 80 Plätzen), so findet der Präsenzunterricht zweizügig statt. In der 1. Woche können alle Studentis des Zugs A zum Präsenunterricht kommen; in Woche 2 können alle Studentis des Zugs B zum Präsenzunterricht kommen. Wer nicht für Präsenz eingeteilt ist, kann dem Unterricht online folgen. Auch wer in Präsenz eingeteilt ist, kann dem Unterricht jederzeit online folgen. Auch wer nicht für Präsenz eingeteilt ist, kann zum Präsenzunterricht kommen, FALLS es freie Plätze gibt: Kommen Sie einfach zum Hörsaal, wenn es freie Plätze gibt, sind Sie herzlich willkommen (es gilt: first come, first serve).
- Sie müssen sich nicht anmelden für Präsenz oder Online.
- Falls die Teilnehmerzahl größer ist als das Doppelte oder es Probleme mit dem Prozedere gibt, erfolgt eine neue Planung.
- Ihr Dozent informiert Sie zu den Details, sobald die Teilnehmerzahl (grob) feststeht.
- Alle Angaben sind vorbehaltlich neuer Corona-Entwicklungen bzw. der Vorgaben der Hochschulleitung dazu.


### Umgangsformen

- Freundlicher Umgang miteinander ist selbstverständlich.
- Selbstverständlich sind auch die grundlegenden Formen der höflichen Miteinanders (Begrüßung, Ansprache mit Namen, bitte/danke sagen, Pünktlichkeit, Verbindlichkeit, ...).
- Bei Nichtwissen oder einem inhaltlichen Fehler wird niemand bloßgestellt oder lächerlich gemacht.
- Um eine Wortmeldung in einer Videokonferenz anzuzeigen, bietet sich die Funktion des Handhebens an.
- In Breakout-Sessions (in Zoom) sollte aktiv mitgearbeitet werden, wer das nicht möchte, betritt den Breakout-Room nicht.
- Spricht man eine Person in einer Videokonferenz an, sollte die Kamera angeschaltet sein.


### Wenn der Unterricht ausfällt

- Im Krankheitsfall werden Sie möglichst frühzeitig informiert (via Moodle); das kann bedeuten, dass Sie am Morgen eine Nachricht bekommen, dass der Unterricht des jeweiligen Tages ausfällt.
- Leider muss der Unterricht in einigen Fällen aufgrund anderer Dienstverpflichtungen des Dozenten entfallen; ein Beispiel sind Berungskomissionen (Auswahlgespräche für neu einzustellende Professor:innen).
- Aufgrund gesetzlicher Feiertage sowie hochschulweit geltenden lehrfreien Tagen fallen jedes Semester einige Tage für den Unterricht aus. Bitte informieren Sie sich auf der zentralen Hochschulseite dazu.
- Falls der Unterricht ausfällt, heißt das *nicht*, dass der für die jeweilige Woche geplante Stoff obsolet ist. Viel mehr ist Ihre Pflicht, den Stoff selbständig zu erarbeiten. Natürlich können Sie bei Fragen jederzeit Ihren Dozenten kontaktieren.


### Salvatorische Klausel

- Diese Hinweise hier gelten nur insofern Ihre Dozentis Ihnen nicht andere Hinweise geben :-)


