



## Grundsätzliches

Die folgenden Hinweise gelten *grundsätzlich*, 
d.h. *soweit nicht anders* in der jeweiligen Prüfung bzw. der jeweiligen Aufgabe angegeben.

Nichtbeachten von Prüfungshinweisen kann zu Punkteabzug oder Nichtbestehen führen.



## Wiederholungsprüfungen

1. Wenn Sie bei einer Prüfung durchgefallen sein sollten, so haben Sie grundsätzlich die Möglichkeit, die *Prüfung zu wiederholen*.
2. Denken Sie daran, sich *rechtzeitig* für Prüfungsleistungen *anzumelden*; beachten Sie die Fristen.
3. Die Termine für die Wiederholungsprüfungen werden stets zusammen/zeitgleich mit denen der regulären Prüfungen bekannt gegeben. 
3. Wird ein Modul im laufenden Semester nicht angeboten, gibt es eine Wiederholungsprüfung. 
3. Relevanter Stoff und formale Bedingungen (wie Prüfungsform) sind *grundsätzlich identisch zur letzten abgehaltenen Prüfung des Moduls* (d.h. sofern nicht anders angegeben). Daher sind Wiederholungsprüfungen vom Anspruch vergleichbar wie die reguläre Klausur. Die Prüfungen sollen möglichst gleich vom Anspruch sein, um Fairness zu gewährleisten.
3. Beachten Sie immer die *Hinweise*, die für die Wiederholungsprüfung angegeben sind. Im Einzelfall keine eine Wiederholungsprüfung von der vorherigen Prüfung stärker abweichen. Es gelten immer die Regeln, die dis Dozenti bei der jeweiligen Wiederholungsprüfung veröffentlicht hat.
2.  Wird ein *Modul im laufenden Semester* angeboten, so gibt es keine Wiederholungsprüfung. Stattdessen können Sie ggf. an der regulären Klausur des Moduls teilnehmen. Es gilt der aktuelle Stoff bzw. die aktuellen formalen Bedingungen. Es ist möglich, dass der Stoff sich dann substanziell ändert; meist halten sich die Änderungen (im Stoff) aber in Rahmen.
2.  Sprechen Sie die *Moduldozentis an für Details zur Prüfung* (bzw. lesen Sie vorab auf jeweiligen Modulseite in Moodle nach).
2.  Manchmal fragen Studentis nach einer *Empfehlung*, ob es besser ist, eine Prüfung zu verschieben, wenn man sich nicht ausreichend vorbereiten konnte. Es ist schwer, eine Empfehlung pauschal abzugeben, es kommt auf den Einzelfall an. Grundsätzlich rate ich aber dazu, Prüfungen nicht zu verschieben: Schließlich könnte in einem folgenden Semester wieder ein unvorhergesehenes Problem auftreten.
2.  Bei Fragen zum *Prüfungsrecht* sprechen Sie bitte die *Studienberatung* an.





## Bearbeitungshinweise 

### Allgemeine Hinweise

1. Verwenden Sie *Standardwerte* (defaults) der R-Funktionen, soweit nicht anders in der jeweiligen Aufgabe verlangt.
2. Findet sich in einer Auswahlliste möglicher Antworten nicht die exakte Lösung, wählen Sie die *am besten passende*.
2.  *Treffen Sie Annahmen*, (nur) wo nötig. 
2.  Die Prüfung besteht auch aus *Single.  bzw. Multiple-Choice*- (MC)-Aufgaben mit mehreren Antwortoptionen.
2.  Bei Multiple-Choice-Aufgaben (MC-Aufgaben) ist zumeist genau *eine* Antwortoption auszuwählen aus vier oder fünf Antwortoptionen.
2.  Im Zweifel ist eine Aussage auf den Stoff, so wie im *Unterricht* behandelt, zu beziehen.
2.  Bei Fragen zu R-Syntax spielen Aspekte wie Enter-Taste o.Ä. bei der Beantwortung der Frage keine Rolle; diese Aspekte dürfen zu ignorieren.
2.  Jede Aussage einer MC-Aufgabe ist entweder richtig oder falsch (aber nicht beides oder keines).
2.  Die MC-Aufgaben sind *nur mit Kreuzen* zu beantworten; Text wird bei der Korrektur nicht berücksichtigt.
2.  Jede Aussage gilt *ceteris paribus* (unter sonst gleichen Umständen). Aussagen der Art „A ist B“ (z.B. "Menschen sind sterblich") sind *nur* dann als richtig auszuwählen, wenn die Aussage *immer* richtig ist.
2.  Falls Sie bei einer Aufgabe mehrere Antworten finden, aber nur nach einer gefragt ist, geben Sie nur eine an. 
2.  Falls mehrere (widersprüchliche) Antworten gegeben wurden, wird im Zweifel die *erst genannte* gewertet.
2.  Die Aufgabenstellung in einer Moodle-Prüfung wird u.U. erst sichtbar, wenn Sie den *Prüfungsbedingungen* zugestimmt haben und die Prüfungszeit begonnen hat.



### Prüfungsstoff

Prüfungsrelevanter Stoff ist alles, was im Unterricht behandelt wurde, sofern es nicht explizit (und schriftlich) als "nicht prüfungsrelevant" gekennzeichnet ist.



### Aufgaben zur Datenanalyse


1.  Je nach Spracheinstellung in Moodle kann es sein, dass Sie als *Dezimaltrennzeichen* ein Komma oder einen Punkt verwenden müssen. Moodle weist Sie, wenn Sie die Aufgabe verlassen, darauf hin, falls eine Zahl nicht als Zahl erkannt wurde.
2.  *Runden* Sie bei Fragen, die auf Anteile abzielen auf *zwei* Dezimalstellen, ansonsten auf eine.
2.  Geben Sie keine Prozentzahlen an, sondern *Anteile* (also nicht “50%”, sondern “0.5” bzw. "0,5").
2.  Bei Aufgaben, die eine Zahl als Antwort verlangen, ist *nur eine Zahl anzugeben* (nicht etwa Buchstaben).
2.  Alle Berechnungen, die *Zufallszahlen* beinhalten, sollen mit *fixierten Startwert* der Zufallszahlen durchgeführt werden. Es ist die Zahl `42` zu verwenden.
2.  Wie auch bei den übrigen Hinweisen gelten diese Maßgaben nur soweit in der Prüfung nicht *explizit andere Hinweise* gegeben wurden.
2.  Wenn *Stichproben simuliert* werden sollen, ziehen Sie $10^3$ Zufallsstichproben.
2.  In einigen Aufgaben kann verlangt sein, dass Sie einen *bestimmten Datensatz in R importieren* sollen. In diesem Fall wird vorausgesetzt, dass Ihnen [diese Bezugsquelle](https://vincentarelbundock.github.io/Rdatasets/articles/data.html) von Datensätzen bekannt ist und dass Sie wissen, wie man einen Datensatz in R importiert.
2.  Achten Sie darauf, R und R-Pakete sowie R-Studio *in aktueller Version* zu verwenden. Das Verwenden älterer Versionen kann (in seltenen Fällen) zu abweichenden Lösungen führen. Im Zweifel beziehen sich alle Aufgaben auf die jeweils aktuellste Version der verwendeten Software.
2.  Wenn Sie *Text eingeben* sollen: Geben Sie *nur Kleinbuchstaben ein*. Geben Sie nur ein einziges Wort ein. Geben Sie keine Leerzeichen ein.



### Besonderheiten zur Bayes-Statistik


1.  Verwenden Sie Methoden der *Bayes*-Statistik für inferenzstatistische Analysen (soweit nicht anders vorgegeben).
2.  Bei Aufgaben zur "*Bayes-Box*" (Erstellung einer Gitterwert-Tabelle) gelten folgende Maßgaben:
  -  Handelt es sich um Parameter mit einem begrenzten Wertebereich (wie etwa *Anteile*), so ist der ganze Wertebereich zu modellieren. Es sind 100 verschiedene Parameterwerte zu berechnen.
  - Handelt es sich um Parameter $X$ mit einem unbegrenzten Wertebereich (wie *normalverteilte* Variablen), so ist der Wertebereich $X-2\sigma \le  X \le X+2\sigma$ zu simulieren.
2.  Nutzen Sie die Software *Stan* in Form des R-Pakets `rstanarm` für Regressionsmodelle auf Basis der Bayes-Methode.
2.  Verwenden Sie immer folgenden *Seed-Wert* bei `stan_glm()`: `42`. Dazu setzen Sie folgenden Parameter `seed = 42` (innerhalb von `stan_glm())`.
2.  Der *Tolerenzbereich* einer Lösung liegt bei 5% des Wertes der Musterlösung. Beispiel: Die Musterlösung liegt bei 100; dann erstreckt sich der Toleranzbereich von 95 bis 105. Tolerenzbereiche werden verwendet für Aufgaben mit Zufallszahlen: Lösungen solcher Aufgaben können schwanken. Wenn Sie allerdings den angegebenen Seed-Wert gesetzt haben, so sollte Ihre (korrekte) Lösung exakt der Musterlösung entsprechen.





## Teilnahmebedingungen

1.  Die Prüfung ist selbständig, also alleine nur durch Sie, *ohne Hilfe Dritter*, zu absolvieren.
2.  Die *Bearbeitungszeiten* der Prüfung sind einzuhalten.
2.  Es dürfen nur die explizit als zulässig gekennzeichneten *Hilfsmittel* verwendet werden.
2.  Die *zulässigen* Hilfsmittel sind: Notizpapier, Stifte, Taschenrechner, Vorlesungsfolien, Skripte, eigene Notizen, Bücher sowie Quellen aus dem Internet.
2.  Die Übernahme von Inhalten Dritter muss also solche gekennzeichnet (*zitiert*) werden. 
2.  Eine wörtliche Übernahme ("*copy-paste*") von Inhalten Dritter (etwa aus einer Quelle aus dem Internet) ist unzulässig.
2.  Bei *technischen Problemen* ist sofort der Prüfer bzw. die Prüferin zu verständigen und das technische Problem zu dokumentieren. Aus der Dokumentation muss der Fehler erkenntlich sein. 
2.  Es ist *untersagt*, die *Prüfung* bzw. Teile daraus (z.B. Prüfungsfragen) zu speichern oder *weiterzugeben.*
2.  Im Übrigen gelten die allgemeinen *Prüfungsregeln*.
2.  Es darf *nicht* mit anderen Personen, insbesondere nicht Prüflingen, *kommuniziert* werden während der Prüfung. Dies gilt auch für den Fall von (vermeintlichen) technischen Problemen. Kontaktieren Sie den Prüfer, wenn Sie meinen, es liege ein technisches Problem vor.



##  Organisatorische Hinweise


### Allgemeines

1.  Etwaige weitere *Stoffeingrenzungen* werden schriftlich bekannt gemacht (auf der Modulseite). Besondere Schwerpunkte gibt es nicht.
2.  Soweit bestimmte Inhalte nicht explizit ausgeschlossen sind, sind alle Inhalte, die im Rahmen des Moduls bearbeitet wurden, *prüfungsrelevant.*
2.  Im Übrigen gelten die Hinweise der *offiziellen Regularien* wie SPO, auf dem Modulsteckbrief und der APO. Bitte kontaktieren Sie die Studienberatung für formale oder rechtliche Fragen. 
2.  Während der Prüfung werden nur Fragen beantwortet, die für die Bearbeitung zwingend nötig sind (etwa bei technischen Problemen).
2.  Es werden keine Fragen der Art "Ist diese Aufgabe klar formuliert?" beantwortet während der Prüfung. Sollten Sie der Meinung sein, eine Frage ist unklar formuliert oder fehlerhaft, so notieren Sie dies bitte (z.B. im Kommentarfeld der Prüfung=. Der Prüfer untersucht im Nachgang die Angelegenheit. Stellt sich eine Frage als fehlerhaft oder unklar formuliert heraus, so wird sie von der Beurteilung herausgenommen.
2.  Eine Teilnahme an der Prüfung ist nur möglich, wenn Sie den Teilnahmebedingungen der Prüfung zustimmen.
2.  Die Aufgabenstellung der Prüfung wird nur während des Prüfungszeitraumes angezeigt.
2.  Beachten Sie eine etwaige Gruppeneinteilung (zu welcher Gruppe Sie zugeteilt sind). 
2.  Beachten Sie die exakte Prüfungsuhrzeit (Beginn, Ende). 
2.  Prüfungszeitraum, Aufgabenstellung und sonstige Materialien können variieren zwischen den Prüflingen etwa aufgrund von Gruppeneinteilungen oder Nachteilsausgleich.
2.  Die zusätzliche Bearbeitungszeit bei Studentis mit Nachteilsausgleich ist in der Aufgabenstellung bzw. der Prüfung in Moodle hinterlegt. Die Zeit wird automatisch um den jeweiligen Faktor erhöht.




### Technische Probleme während der Prüfung

Im Falle eines technischen Problems auf Seiten der *Prüfungsinfrastruktur* ist sofort der Prüfer zu informieren. Ein Beispiel für so ein Problem wäre etwa der Ausfall von Moodle. Der technische Fehler ist zu dokumentieren (z.B. Screenshot) und die Dokumentation ist einzureichen. Bitte beachten Sie, dass der Prüfer bzw. die Hochschule keine Gewähr übernimmt für Probleme mit Ihrer eigenen Ausstattung. 



### Zeitrahmen der Prüfung

Die Prüfung beginnt und endet zu einem festen Zeitpunkt. Sie sind selber verantwortlich, die Prüfung zur korrekten Zeit zu beginnen und zu beenden (einzureichen). Verspätete Abgaben werden u.U. als nicht bestanden gewertet. Die Dauer der Prüfung wird Ihnen von Ihrer Prüferin bzw. Ihrem Prüfer bekannt gegeben. 












### Plagiatskontrolle


Ihre Prüfungsarbeiten können auf Plagiate hin untersucht werden. Dabei kommen auch automatisierte Verfahren zum Einsatz. Ihre Arbeiten werden dabei nicht online gestellt und auch nicht Dritten zugänglich gemacht. Alle Prüfungen finden auf Rechnern statt, zu denen nur die Prüfer/innen Zugang habe. Es werden keine persönlichen Daten (von Ihnen) weitergegeben.

Bitte beachten: Angenommen in den Projektarbeiten von Studenti A und B werden (substanzielle) Überlappungen gefunden. In dem Fall ist davon auszugehen, dass beide Studentis getäuscht haben: eine/r hat abgeschrieben, der/die andere hat die eigene Arbeit dafür bereitgestellt. Daher wird in diesem Fall u.U.  bei beiden Studentis der Plagiatsfall festgestellt und geahndet (z.B. mit "nicht  bestanden" bewertet). Die genauen Konsequenzen legt die Prüfungskommission im Einzelfall fest.

Lassen Sie es auf keinen Fall soweit kommen: Schreiben Sie nicht ab und lassen Sie niemanden von Ihrer Arbeit abschreiben. 

Eine faire Prüfung heißt: Gleiche Chancen für alle, und gute Leistung soll belohnt werden, Täuschung nicht.






## Open-Book-Prüfungen 

### Was ist das: Open-Book?

Einige Prüfungen werden als “Take-home-Prüfung” im “Open-Book-Format” geschrieben. Was bedeutet dies?

“Take-home-Prüfung”: Sie bearbeiten die Prüfung in Ihrem privaten Umgebung in Moodle oder in Räumlichkeiten der Hochschule. Eine Überwachung per Kamera findet nicht statt.

“Open-Book-Prüfung”: Sie dürfen Hilfsmittel wie Bücher und Folien während der Prüfung nutzen. 

Ihre Prüferin/Ihr Prüfer informiert Sie über das Format Ihrer Prüfung.

Die Prüfungsleistung ist selbständig von Ihnen zu erbringen.
Jegliche Unterstützung Dritter während der Prüfung ist untersagt.




### Technische und organisatorische Anforderungen einer Open-Book-Prüfung

Um an einer Open-Book-Prüfung teilzunehmen, benötigen Sie IT-Ausstattung sowie Räumlichkeiten. 
An IT-Ausstattung benötigen Sie einen Computer mit Internetanschluss; ein Smartphone reicht nicht aus. 
Nutzen Sie Ihr eigenes Gerät (Computer) für die Prüfung; die Hochschule stellt Ihnen keinen Computer zur Verfügung. 
Sie benötigen keine Webcam und kein Mikrofon. 
Ein Tablett oder Smartphone reicht nicht für die Prüfung. 
An Software benötigen Sie Zugang zu Ihrem Moodle-Konto, was einen aktuellen Internet-Browser voraussetzt. Zu den organisatorischen Anforderungen gehören ein Raum, in dem Sie die Prüfung ungestört bearbeiten können sowie ein Internetanschluss zum Bearbeiten der Klausur in Moodle. 
Bitte benutzen Sie während der Prüfung nicht den Zurück-Button in Ihrem Browser, wenn Sie zu einer vorherigen Frage zurückgehen wollen. 
Nutzen Sie die in der Prüfung zur Verfügung gestellten Funktionen/Buttons dafür (z.B. in Moodle).



### Prüfungsrecht

Für die Open-Book-Prüfungg gilt die aktuelle Prüfungsordnung; die Open-Book-Prüfung fällt *nicht* unter die BayFEV. 




### Datenschutz

Persönliche Daten werden an einer Stelle übermittelt: Moodle (über bzw. in Ihrem Konto). 
Es findet keine Überwachung statt, weder kamaragestützt, akustisch oder softwaregestützt.










## Korrekturhinweise




### Typische Fehler in der Prüfung

1.  *Rechtschreibfehler* Manchmal muss man genau hinschauen, und leicht vertippt man sich: So heißt der Datensatz vielleicht `tips` und die Spalte, um die es Ihnen geht `tip` (oder war es umgekehrt?). Oder die Spalte heißt `bill_length` aber Sie schreiben `bill_lenght`.
2.  *Datensatz nicht richtig importiert* Ob ein Datensatz richtig importiert ist, erkennen Sie daran, ob er im Reiter "Environment" angezeigt wird. Außerdem können Sie dort den Datensatz anklicken, um zu einer Tabellenansicht des Datensatzes zu gelangen. Dort können Sie erkennen, ob z.B. die Anzahl der Spalten korrekt ist (und nicht etwa nur eine) oder z.B. ob die Spaltennamen korrekt sind.
2.  *`data(datensatz)` ohne vorher das zugehörige R-Paket gestartet zu haben*: Mit `data(datensatz)` können Sie den Datensatz `datensatz` *nur* dann verfügbar machen, wenn das Paket, in dem `datensatz` "wohnt", mit `library(paketname)` gestartet worden ist. So "wohnt" z.B. `penguins` im Datensatz `palmerpenguins`. [Hier](https://datenwerk.netlify.app/post/pfad/pfad/) finden Sie eine Übung (und weitere Erklärung) zum Importieren von Daten in R am Beispiel des Datensatzes `penguins`.
2.  Verwenden einer *Funktion, ohne das zugehörige R-Paket* vorab gestartet zu haben.
2.  Das Laden *zu vieler R-Pakete*, die gar nicht benötigt werden, mit dem Ergebnis, dass es mehrere Funktionen des gleichen Namens gibt (z.B. `filter()`). Das führt dann zu Verwirrung, da dann z.B. nicht die Funktion `filter` aus `tidyverse` (`dplyr`) verwendet wird, wie Sie annehmen, sondern eine Funktion gleichen Namens aus einem anderen Paket, das Sie auch gestartet haben. Tipp: Starten Sie nur die Pakete, die Sie für die Aufgabe benötigen. Zumeist sind das immer die gleichen wenigen Pakete.





### Bitte formulieren Sie Beanstandungen nachvollziehbar

Falls Sie einen Fehler in einer Aufgabenstellung finden (die der Prüfer zu bestanden hat): Freuen Sie sich! In diesem Fall wird zu Ihren Gunsten entschieden.

Damit ich Ihre Beanstandung prüfen kann, ist es nötig, dass ich Ihre *Beanstandung* nachprüfen kann: *Zeigen* Sie mir meinen Fehler. 
Es reicht *nicht* zu sagen "es hat bei mir nicht funktioniert". 
Wenn Sie etwa der Meinung sind, dass es die Variable "year" im Datensatz "penguins" nicht gebe, dann schicken Sie mir den R-Code,
der an ansprechender Stelle einen Fehler aufwirft (aber *ansonsten lauffähig* ist). 
Ein Screenshot kann in einigen Situationen helfen,
wenn aber nur ein Teil der Syntax zu sehen ist, ist er nicht ausreichend: Wenn der Befehl `data(penguins)` nicht funktioniert, 
so ist zu prüfen, ob Sie vorab mit `library(palmerpenguins)` das relevante Paket gestartet haben. 
Andernfalls kann `data(penguins)` nicht funktionieren und der Fehler läge damit bei Ihnen.

[Hier](https://data-se.netlify.app/2022/01/31/erbie-einfache-reproduzierbare-beispiele-ihres-problems-mit-r-syntax/) finden Sie Hinweise für *e*infache, *r*eproduzierbare *Bei*spiele (ERBies); vgl. Sauer (2019), Kap. 3.8.2 (S. 33).



Die gleiche Messlatte lege ich an mich an: Ich stelle eine Musterlösung (bei der Einsichtnahme) zur Verfügung, die reproduzierbar die Lösung aufzeigt. Sprich: Wenn der R-Code bei mir durchläuft, so wird er auch bei Ihnen durchlaufen.



### Hinweise zu Scheinmängeln

Immer wieder kommt es vor, dass Studierende Beanstandungen zu einer Prüfung vorbringen. Teilweise sind diese gerechtfertigt, teilweise nicht. Im Folgenden sehen Sie eine Auswahl an *nicht* gerechtfertigten Beanstandungen, also nur scheinbaren Mängeln, keine wirklichen Mängel, in einer Prüfung.

-   "*Das zu wählende Vorgehen war nicht 100% klar*" -- Wenn Sie der Meinung sind, dass das zu wählende Vorgehen (zum Lösen der Aufgabe) nicht komplett klar ist, treffen Sie Annahmen und weisen Sie darauf hin, dass Sie Annahmen getroffen haben. Zum anderen halten Sie sich an das Vorgehen aus dem Unterricht (bzw. den Unterlagen und der Literatur, die im Unterricht verwendet wurde). Eine andere Situation läge vor, wenn die Aufgabe nicht lösbar ist ohne weitere Angaben lösbar ist("Ist ein Effekt bei n=100 signifikant?"). Im Falle einer nicht lösbaren Aufgabe liegt der Fehler beim Prüfer.

-   "*Ich sollte einen Punkt (ein Komma) als Dezimaltrennzeichen verwenden, aber Moodle hat ein Komma (einen Punkt) verlangt!*" -- Je nach Spracheinstellung in Moodle kann es sein, dass Moodle nur einen Punkt als Dezimaltrennzeichen bzw. ein Komma als Dezimaltrennzeichen verwendet. Moodle weist Sie aber darauf hin, wenn eine Zahl nicht als Zahl erkannt wird, und zwar wenn Sie zur nächsten Aufgabe geben. Sie können also ohne Probleme den Fehler korrigieren. Darüber hinaus ist bei den Prüfungshinweisen vorab auf diesen Punkt verwiesen.

-  "*Ich sollte die Lösung als Anteil angeben, habe sie aber in Prozent angeben, also `42%` anstatt von `0.42`*". -- Da die angegebene Lösung (als Prozentzahl) falsch ist, kann sie nicht als richtig gewertet werden.



### Prüfungseinsicht

Eine Prüfungseinsicht wird jedes Mal bereit gestellt (online).
Der Termin wird allen Prüflingen rechtzeitig bekannt gegeben.
Zur Prüfungseinsicht öffnen Sie bitte Ihre Aufgabenstellung.
Die Musterlösung wird dann angezeigt.






