



### Grundlagen

1. Alle *Lehrmaterialien* stelle ich vor dem Unterricht *online* bereit.
2. Alles prüfungsrelevante Material ist *verschriftlicht* und die *Prüfungsmodalitäten* sind *frühzeitig* (schriftlich) bekannt gemacht.
4. *Eigenstudierbarkeit*: Das Modul ist auch ohne Besuchen des Unterrichts studierbar.
5. Wenn möglich, wird der Präsenzunterricht durch *Live-Streaming* ergänzt.
6. Für den Stoff existiert eine *Gliederung* und *Lernziele*, so dass ein roter Faden ersichtlich ist.
7. Für jede Unterrichtseinheit ist ein *Stundenthema* vorgegeben.
8. Es werden für (möglichst) alle Unterrichtseinheiten *Aufgaben* bereitgestellt, so dass Lernende üben können und über den eigenen Fortschritt im Bilde sind.
9. Praxisbezug wird sichergestellt, z.B. durch *Fallstudien.*
10. Infos an die Studierenden eines Moduls werden durch ein *Nachrichtensystem* zugestellt.
11. Der Unterricht ist von einer *dialogischen Haltung* geprägt, nicht von Frontaltunerricht.



    

### Lehrkonzept

In der "Vorlesung" wird im Schwerpunkt *nicht* ein Folienskript "vorgelesen". Solcher Inhalt steht oft vorab als Video zur Verfügung (s. Links im Themenüberblick).
 Stattdessen steht in der "Vorlesung" die Durcharbeiten und Vertiefen des Stoffes im Vordergrund, nicht aber das Vortragen des Stoffes.
Warum wird die Literatur oder das Folienskript nicht im Unterricht vorgetragen? Zum einen können Sie das alleine besser (in eigener Geschwindigkeit, mit Pausen nach Gusto, zu beliebiger Zeit und beliebigem Ort, so oft wiederholt wie Sie mögen). Zum anderen ist der Lerngewinn beim passiven Zuhören gering. Das Durchdenken, Durcharbeiten, "Durchfragen" des Stoffes ist es, was Ihnen den meisten Gewinn beschwert. Entsprechend liegt auf dem aktiven, gemeinsamen Arbeiten der Schwerpunkt.
Das heißt nicht, dass es nie Vorträge vom Dozenten im Unterricht gäbe; manchmal schon. Aber aus genannten Gründen liegt der Fokus des Unterrichts im aktivierenden Arbeiten.
Natürlich können im Unterricht jederzeit die Fragen der Studentis zum Stoff besprochen werden. Seien Sie ausdrücklich ermuntert, Ihre Fragen im Unterricht zu formulieren, vorzugsweise im direkten Gespräch, aber alternativ anonym (wie Frag-Jetzt).
In der Übung liegt der Schwerpunkt zumeist auf dem Bearbeiten von Aufgaben.



### Lerntipps

Damit Sie vom Unterricht maximal profitieren, ist es essenziell, dass Sie aktiv mitarbeiten. Ein "Nur-Zuhören" nimmt Ihnen einen Gutteil des Nutzens des Unterrichts. Sie lernen nur zum kleinen Teil vom Zuhören; der größte Teil des Lernerfolgs kommt vom Selber-Erarbeiten!
Bitte stellen Sie Ihre Kamera (Webcam) an, wenn Sie Kommilitonis oder den Dozenten ansprechen. Das ist der Güte der Kommunikation zuträglich.
Bereiten Sie den Stoff vor und arbeiten Sie ihn gewissenhaft nach.
Das gemeinsame Arbeiten in einer (virtuellen) Lerngruppe ist sehr nützlich.
Tauschen Sie sich im Diskussionsforum auf unserer Modulseite aus; gehen Sie in den Diskurs mit den Kommiliton/innen. Falls Sie (im Internet) nützliches Material gefunden haben, können Sie es auch in das Forum einstellen. 
Nutzen Sie das Diskussionsforum auch, um den Dozenten Fragen zu stellen. 
Meine Erfahrung zeigt mir, dass der Lernerfolg zwar auch von der Lehrperson abhängt, aber entscheidend ist der Wille eines/r Studierenden/r, selbst aktiv zu lernen. Ich glaube, dass Sie gut mit Material ausgestattet sind, um selbständig und mit Erfolg zu lernen.
Anbieter wie Google stellen (teilweise) kostenfreie Angebote zum kollaborativen Arbeiten zur Verfügung (Google Docs). Behalten Sie hier den Datenschutz im Blick.





### "Einstreuer"

In jedem Kapitel, gibt es eine Reihe von Lehrmaterialien,
sozusagen orthogonal zum Inhalt, die das Verstehen und die Umsetzung anreichernd unterstützen,
das sind:

- Praxisbezüge
- Beispiele
- Definitionen
- Hinweise
- Achtung, Fehlerquelle
- Besonders Wichtiges
- Literatur
- Aufgaben
- Lernziele
- Softwarehinweise
- Überblick im Lernpfad
- Exkurse
- Blick in die Forschung




### "Buch 2.0"

Modernes HTML bietet eine Reihe von technischen Vorteilen,
dazu gehört, dass verschiedene Medien eingebettet werden können.
In diesem Buch werden folgende verwendet:

- Text, Bilder, Tabellen - voll referenziert
- R-Syntax und Ausgabe
- Animationen
- Videos
- Gleichungen und R-Syntax-Listings - voll referenziert
- Copy-Paste-Funktion (für R-Syntax)
- Code-Fold, so dass die R-Syntax und Exkurse nur nach Aufklappen sichtbar sind (und ansonsten nicht stören)


### Barrierefrei

Auf Lehrinhalte wird oft zugegriffen, zumindest hofft das der Autor.
Gehen wir davon aus, dass ein Kurs 15 Wochen dauert, und pro Unterrichtsstunde UE Material "im Wert von 50 Folien" angesehen werden, so kommt man auf 50 Klicks oder Kontakte,
mal 4 UE pro Woche ergibt `r 50*4*15` Kontakte mit Material pro Studi.
Bei so vielen Kontakten bekommt das Wort *barrierefrei* eine hohe Bedeutung.

Aus diesem Grund steht das Buch steht frei im Netz, genauso die Aufgaben und die Lösungen.
Damit ist ein einfacher Zugriff möglich.
Außerdem gibt es eine hohe Anzahl an URLs: Nicht nur pro Seite,
sondern auch pro Abschnitt und für alle besonderen Objekte wie Tabellen und Diagramme.


### Kompetenzorientiert

Es gibt viele Übungsaufgaben, anhand derer die Studentis ihren Lernfortschritt überprüfen können. Diese Aufgaben haben zumeist eine klare, kurze richtige Antwort (oft im MC-Format),
so dass einfach eine Punktzahl ausgegeben kann für ein maximal klares Feedback an die Studentis.
Außerdem gibt es aber auch Fallstudien, für komplexere und reichhaltigeres Einüben der Kompetenzen.
Schließlich ist die Prüfungsform komplett kompetenzorientiert gehalten und gleichzeitig maximal objektiv durch Berechnen der Vorhersagegüte.



### Fokus auf Modellierung

Modelle stehen, auch in modernen und fortgeschrittenen Anwendungen, im Mittelpunkt der Statistik als (angewandte) Wissenschaft. 
Gleichzeitig sind Sie einsteigerfreundlich, denn jeder Mensch kennt Modelle aus dem alltäglichen Leben. 
Darüber hinaus lassen sich Modelle perfekt verbinden mit zentraler statistischer Methodik,
namentlich dem Allgemeinen (Generalisierten) Linearen Modell (ALM bzw GLM).
Aus diesem Grund wird das ALM als zentrale methodische Blaupause verwendet.
Anstelle von einer Vielzahl statistischer Testverfahren, die letztlich aber fast immer Spezialfälle des ALM darstellen, wird hier zu zugunsten der Einfachheit,
konzeptioneller Klarheit (und wissenschaftlicher Ästhetik) alles Modellieren auf dem ALM aufgebaut.

### Praxisbezug

In allen Kapiteln werden Themen aus der (künftigen) Berufswelt der Teilnehmis herangezogen.
Ganz zu Beginn eines neuen Themas wird davon abweichend immer wieder von extrem einfachen (aber auch lebensweltlich relevanten) Beispielen Gebraucht gemacht,
zu Gunsten eines einfachen Einstiegs in neue Materie.
Auf mathematische Herleitung wurde aus dem gleichen Grund weitgehend verzichtet.


### Anschaulichkeit

Es wurde versucht, möglichst viele Sachverhalte schematisch in Diagrammen zu illustieren.
Damit ist bei weitem nicht nur gemeint, statische Diagramme aufzuzeichnen.
Vielmehr ist versucht worden, zentrale theoretische Konzepte in einfachen Diagrammen widerzuspiegeln.
Dieser eher informelle Wege nimmt zwar Einbußen an Präzision und inhaltlicher Tiefe in Kauf, 
öffnet aber gerade für in symbolischer Verarbeitung schwächeren Studentis einen Zugang.
Darüber hinaus haben Diagramme bzw. Schemata den didaktischen Vorteil,
dass sie sich hervorragend eignen für Unterricht im Hörsaal oder Seminarraum:
Man betrachtet zusammen ein Bild und diskutiert darüber,
das Konzept ständig vor Augen.



### Bildreichtum

Dieses Buch verwendet viele Bilder. Das hat vor allem den Grund, das Lehren zu erleichtern.
Es ist dröge - beim Zuhören und beim Lehren - sich durch Textwüsten und Stichpunkt-Wälder zu kämpfen.
Viel angenehmer ist es (nach meiner Erfahrung), 
wenn die Lehrperson anhand eines guten Diagramms den wesentlichen Punkt erläutert.


### Literatur

Pro Thema wird Literatur ausgewiesen, die den Stoff ausführlicher erläutert oder auf vertiefende Aspekte eingeht (Aspekte, die über den Stoff und die Lernziele hinausgehen).
Quellen der Inhalte sind pro Kapitel im Literaturverzeichnis aufgeführt.






### Für Autodidakten geeignet

Folien sind zu knapp, um sie ohne Erläuterung zu verstehen. Wären Sie ausführlich, würde man sie "Buch" nennen. 
Dieses Buch versteht sich als eine Art "Prosa-Skript", also ausformuliertes Skript zur Begleitung des Unterrichts. 
Nicht zur zur Begleitung: Dieses Skript ist zwar "dünner" als ein Buch, aber versucht, die wesentlichen Inhalte abzudecken.
Außerdem sollen nicht nur Inhalte abdeckt sein, sondern auch die Kompetenz entwickelt werden, etwa durch Aufgaben.







