

---
title: "Prüfungshinweise"
params:
  pruefungsleistung: Seminararbeit
---    



*Die folgenden Prüfungshinweise gelten nur insoweit, dass Ihnen Ihr/e Dozent/in nicht anderweitige Hinweise gegeben hat.*


## Prüfungsgegenstand




### Grundlagen


1. Die *Prüfungsleistung* wird rechtzeitig von der/dem Prüfer/in definiert und an geeignetem Ort bekannt gegeben.
    
2. Es wird erwartet, dass Sie als Versuchsperson an den *Studien der Kommilitonis teilnehmen*, falls nötig.
    
2. Sie führen eine *eigene empirische Studie* durch und verfassen dazu einen Bericht; dabei stützen Sie sich i. d. R. auf selber erhobene Daten.

2. Gegenstand der Seminararbeit ist die *Dokumentation aller Phasen der Studie* des jeweiligen Forschungsteams. 


### Formale Anfordungen 

1. Der Umfang der Arbeit umfasst im *Hauptteil* *6000* Wörter bei Gruppenarbeiten und *4000* Wörter ein Einzelarbeiten, plus/minus 10%. *Hauptteil* ist definiert als der Text von Einführung bis zum Ende der Diskussion. 

2. Die Methoden des *wissenschaftlichen Arbeiten* in Recherche, Zitat und Darstellung werden angewandt.

3. Wenden Sie die Methoden *quantitativer* Datenanalyse an.

4. Textsatz und (gestalterische) *Formatierung* der Seminararbeit orientieren sich an dem bereitgestellten *Leitfaden* bzw. den Hinweisen.

5. Gestaltungsaspekte, die nicht im bereitgestellten Leitfaden aufgeführt sind, sind nach den Vorgaben der APA (neueste Version) anzulegen.

6. Die Arbeit kann in *deutscher* oder englischer Sprache eingereicht werden.


6. Auf dem *Titelblatt* ist u.a. anzugeben
    - Matrikelnummer/n sowie Nach- und Vorname/n aller Autoris (wichtig!)
    - Titel der Arbeit
    - Modulname

7. Wenn die Prüfung aus einer Seminarbeit besteht oder eine Seminarleistung beinhaltet, ist diese *nur online*, nicht ausgedruckt einzureichen.

8. Bei der Benotung wird die *Kenntnis der Inhalte der Veranstaltung* (inkl. dieses Skripts) vorausgesetzt.

9. Bei der *Anmeldung* ist der Titel anzugeben; der *gleiche Titel* muss sich auch auf der eingereichten Arbeit finden.

10. Eine eingereichte Arbeit *kann nicht wieder zurückgezogen* werden.



14. *Open Science*: Reichen Sie die Rohdaten und ggf. Syntax (elektronisch) ein. Verweisen Sie ggf. im Anhang auf eine Datei, die Sie hochladen, in der die entsprechenden Informationen zu finden sind.

15. Reichen  Sie folgende *zwei Dateien* als Prüfungsleistung ein: a) Die Seminararbeit als PDF-Datei sowie b) den Anhang bzw. ergänzende Materialien als eine ZIP-Datei.

16. Das Thema muss einen *direkten empirisch-psychologischen Bezug* haben; die Forschungsfrage muss psychologisch relevante Aspekte adressieren.

17. Bitte sprechen Sie Ihr:e Dozenten/in für Fragen des *Nachteilsausgleichs*.

18. *Nichteinhaltung* der Regeln bzw. der Hinweise kann zu *Nichtbestehen* oder einer schlechterer Note führen.

19. Bitte beachten Sie etwaige *Anmeldefristen* für die Anmeldung zur Prüfung als auch ggf. zur Anmeldung in einzelne Arbeitsgruppen.

20. Soweit nicht anders von der Lehrperson gesagt, gelten die *offiziellen* Anmeldefristen der Hochschule.

21. Vermeiden Sie *kurzfristigen* Upload von Prüfungsleistungen kurz vor dem Verstreichen der  Einreichefrist – falls technische Probleme auftreten, können diese u. U. nicht mehr gelöst werden.

22. Die Dozentis führen *keine Vorab-Korrektur* von laufenden Prüfungsleistungen durch. Fragen, die einer Vorab-Korrektur Ihrer Arbeit nahe kommen (und daher nicht beantwortet werden), sind z. B.: „Ist mein Fragebogen so o.k.?“, „Passt das so?“, „Können Sie mal drüber schauen, ob ich so anfangen kann?“, „Passen meine Hypothesen zur Theorie?“, „Hab ich was vergessen?“, „Ist die Gliederung so richtig/vollständig?“ ...

23. Fragen zum Stoff werden im Unterricht jederzeit beantwortet. Sprechen Sie die Dozentis auch gerne vor oder nach dem Unterricht persönlich an.

24. Aus Gründen der Fairness werden inhaltliche Fragen von Studierenden nur öffentlich, z. B. im Unterricht oder im Online-Forum, beantwortet (nicht per Mail).


## Benotung


### Aspekte der Benotung

1. Es wird eine Gesamtnote vergeben und ggf. drei Teilnoten.

2. Die Gesamtnote setzt sich aus drei Teilaspekten zusammen.

2. Die drei Teilaspekte sind
    - *Formalia* (u.a. Aufbau, Gestaltung, Rechtschreibung, Zitierweise, Literaturverzeichnis, Umfang)
    - *Methodik* (u.a. Methodenauswahl, Methodenanwendung, Interpetation)
    - *Inhalt* (u.a. Gliederung, Argumentation, Literaturnutzung, sprachlicher Ausdruck, Problemlösung, Reflexion)
    
2. Falls Teilnoten vergeben werden, muss sich die Gesamtnote *nicht* als arithmetisches Mittel der Teilnoten ergeben.

    
    
### Anspruch

1. Anspruch an eine gute Seminararbeit
    - Überwiegende Verwendung von Literatur hoher Qualität (Fachartikel, peer-reviewed)
    - Ca. 30 Quellen oder mehr im Literaturverzeichnis bei Einzelarbeiten; Faktor 2 bei Gruppenarbeiten
    - Stichprobengröße (ca.)
      - Experimentell: Between-Design 50 Fälle, Within-Design: 20 Fälle bei Einzelarbeiten; Faktor 2 bei Gruppenarbeiten
     - Beobachtend: 100 Fällebei Einzelarbeiten; Faktor 2 bei Gruppenarbeiten
    - Designumfang (ca.)
      - Experimentell: 2-3 Variablen
      - Beobachtend: 3-4 Variablen bei Einzelarbeiten; Faktor 2 bei Gruppenarbeiten






### Beispiele für Fehler

Substanzielle Fehler können zum Durchfallen oder zum deutlichem Abwerten der Note führen. Beispiele für solche Fehler sind:

1. Formalia

 - Die Textlänge (Hauptteil) ist zu kurz – ca. 20 % unter der formal angegeben Soll-Länge.
  - Es liegen viele Zitierfehler im Text vor (z. B. 30 % oder mehr bzw. 10 oder mehr Fehler).
  - Es liegen viele Fehler im Literaturverzeichnis vor (z. B. 30 % oder mehr bzw. 10 oder mehr Fehler).
  - Es wurde die geforderte empirische Methode nicht verwendet.
  - Es findet sich ein oder mehrere Plagiate (weitere Konsequenzen sind möglich).
  - Die Versionen der Gruppenmitglieder (bei Gruppenarbeiten) unterscheiden sich.
  - Es finden sich nicht zitierte Quellen im Literaturverzeichnis. 
    
2. Inhaltliche Mängel

  - Das Literaturverzeichnis ist sehr kurz (weniger als 50% der empfohlenen Zahl von Quellen).
  - Die Qualität des Literaturverzeichnisses ist gering (über 50 % Quellen von zweifelhafter Qualität, z. B. aus Ratgeber-Büchern).
  - Die Lesbarkeit ist aufgrund der optischen Gestaltung oder gravierender Sprachmängel stark eingeschränkt (z. B. viele Rechtschreibfehler).
    
3. Methodische Mängel

  - Es wird keine Inferenzstatistik verwendet.
  - Zentrale Koeffizienten werden falsch interpretiert.
  - Es wird keine/kaum Deskriptiv-Statistik berichtet.
  - Forschungsfragen bzw. Hypothese und Datenanalyse passen nicht zusammen.
    
    
    
### Merkmale einer sehr guten Seminararbeit

1. Formales

  - Die Richtlinien zur Gestaltung von wissenschaftlichen Texten wurden (fast) vollumfänglich umgesetzt. Insbesondere finden finden sich (fast) keine Zitierfehler im Text und im Literaturverzeichnis.
  - Rechtschreibung, Zeichensetzung und Grammatik sind (fast) fehlerfrei.
  - Gestaltung und Aufbau der Arbeit ist dem flüssigen Lesen zuträglich (z. B. optisch übersichtlich gestaltet und nicht weitschweifig sondern prägnant formuliert).

2. Methoden

  - Es wurden angemessene Methoden ausgewählt und diese richtig angewendet und die Ergebnisse korrekt interpretiert.
  - Die eingesetzte Methodik zeichnet sich durch hohe Breite und Tiefe aus.
  - Es wurde sehr viel empirisches Material (z. B. befragte Personen) ausgewertet.

3. Inhalt

  - Es wurde viel Literatur von hoher Qualität rezipiert.
  - Ein roter Faden ist klar ersichtlich.
  - Die Arbeit zeichnet sich nicht nur durch hohes Fachwissen, sondern auch durch wohl überlegte Argumentation aus.



### Aus der Checkliste eines Gutachters

- Wissen

  - Wurden die wesentlichen Inhalte des Themas berücksichtigt?
  - Sind hochwertige (und genügende) Quellen zu Rate gezogen worden?
  
- Denken

  - Reihen sich nur Zusammenfassungen aneinander oder ist Denkarbeit erkennbar?
  - Wurde das eigene Vorgehen angemessen kritisiert?
  - Wurde diskutiert, verglichen, bewertet, weitergeführt, erörtert, analysiert ... ?
  - Zeugt die Arbeit von eigenen Ideen und eigenem Denken?
   - Wurde selbständig gearbeitet?
   
- Schreiben

  - Ist Rechtschreibung, Zeichensetzung und Grammatik korrekt?
  - Ist der Text „im Fluss“ – gut lesbar, stringent und folgerichtig?
  
- Methodik

  - Wurden die richtigen wissenschaftliche Methoden korrekt eingesetzt?
  - Zeugt das methodische Vorgehen von Können und Kreativität?
  - Ist die Studie nachprüfbar anhand des Berichts?
  
- Polieren

  - Sind die Formalia erfüllt (z. B. korrektes Zitieren inkl. Literaturverzeichnis)?
  - Sind Text, Abbildungen, Tabellen etc. ansprechend formatiert?  
  
  
### Typische Fehler

1. Fachlich dünn: Die Anzahl von guten Quellen (z. B. Fachartikel) ist gering; der Autor kennt sein Thema zu wenig. Es findet kaum Rückbezug der eigenen Studie/Daten auf die Literatur statt.

2. Stoff nicht ausreichend reflektiert: Es werden Fakten aneinander gereiht, ohne dass ist, ob sich mit dem Stoff auseinander gesetzt wurde (z. B. werden Stärken/Schwächen einzelner Texte nicht diskutiert).

3. Formalia fehlerhaft: Durch „Äußerlichkeiten“ werden Punkte verschenkt (z. B. pixelige Grafiken, optisch schlecht aufgelockerte Texte, „Löcher“ im Textfluss; Fehler im Literaturverzeichnis).

4. Zahlen irreführend präsentiert: Statistiken wie werden unvollständig präsentiert oder die Anzahl der Nachkommastellen ist zu hoch oder inkonsistent.

5.  Selbstkritik fehlt: Stärken und Schwächen der eigenen Art werden nicht diskutiert.


  
### Tipps für eine erfolgreiche Seminararbeit

#### Reflexion: Bereichen Sie die Welt mit Ihren Gedanken

- Ein Hauptfehler vieler Hausarbeiten liegt darin, dass sie nur andere Texte nacherzählen. Wo liegt da der Mehrwert?

-  Der Mehrwert eines wissenschaftlichen Textes liegt in der Neuartigkeit der Gedanken: Kritisieren Sie bestehende Theorien, vergleichen Sie sie, arbeiten Sie das Wesentliche heraus. Übrigens: Auch eine Wiederholungsstudie lohnt sich.

-  Legen Sie Ihre Forschungsfrage offen, beantworten Sie sie explizit.

- Explizieren Sie Ihre Hypothesen (konkret und operationalisiert)

- Sparen Sie auch eine kritische Aufarbeitung Ihrer eigenen Arbeit nicht aus. „Kritisch“ heißt positiv und konstruktiv negativ Rückmeldungen geben.

- Das „Fazit“ Ihrer Arbeit ist nicht eine Zusammenfassung Ihres Textes sondern die Überlegung, wohin Sie Ihre Gedanken geführt haben.

- Zur Reflexion gehört auch, dass Sie an den Nutzen des Lesers denken – was bringt ihm die Lektüre Ihres Texts? Sagen Sie z. B. anfangs, warum sich Ihr Thema „lohnt“!

- Unterscheiden Sie zwischen Beschreibung von Ideen (oder [Ihren] empirischen Ergebnissen) und deren Beurteilung.

- Beziehen Sie Ihre Ergebnisse/Daten auf die Literatur.
  
  
  
#### Fachwissen: Zeigen Sie, dass Sie sich auskennen


- Nachdem Sie darüber nachgedacht haben, was ein lohnendes Thema ist, recherchieren Sie nach Literatur.

- Ohne einen kundigen (und aktuellen) Überblick über den Stand der Forschung können Sie keine verlässlichen Aussagen treffen – und keine gute Arbeit schreiben.

- Scheuen Sie sich nicht Fachartikeln; machen Sie sich die Qualität Ihrer Literaturstellen bewusst.

- Destillieren Sie aus der Vielfalt der Texte die Essenz der Ideen heraus – die Details sind nicht so wichtig.

- Zeigen Sie keine Bäume, sondern den Wald. Zeigen Sie keine unumstößliche Wahrheit, sondern mehrere Blickwinkel (z. B. unterschiedliche Definitionen). Verknüpfen Sie den Gegenstand mit anderen Theorien.

- Ihr Fachwissen zeigen Sie auch dadurch, dass Sie kritisch zu den Texten oder dem Forschungsstand Stellung nehmen.

- Erläutern Sie nicht die Hintergründe Ihrer Methoden im Detail. Das steht schon in den Lehrbüchern bzw. ist nicht üblich.

- Gehen Sie auf wesentliche Befunde oder Theorien des Fachgebiets ein, soweit relevant bzw. zweckdienlich.  
  
  
  
#### Fluss: Der Text soll elegant fließen

- Begründen Sie Ihr Vorgehen.

- Man soll Dinge so einfach wie möglich ausdrücken, aber nicht einfacher (Einstein). Verwechseln Sie nicht komplizierte Wörter mit gehaltvollem Inhalt.

- Jedes Kapitel und jeder Absatz sollte genau eine Frage beantworten.

- Achten Sie auf ein gefälliges Äußeres Ihres Texts: Layout, Abbildungen, Schriftbild, leere Stellen im Blocksatz etc. machen einen Eindruck auf den Leser. Schaubilder helfen oft. Spiralbindung bietet sich an. Absätze sollten nicht zu lang sein (Textwüsten schläfern ein).

- Die Gliederung soll den Fluss Ihrer Argumentation wiedergeben.

- Schreiben Sie elegant: Z. B. meiden Sie Passivsätze; schreiben Sie aktiv. Wechseln Sie kurze mit langen Sätzen ab. Meiden Sie Amtsdeutsch wie der Teufel das Weihwasser. Ein guter Titel hat selten geschadet. Verwenden Sie die „Ich-Form“ sparsam; genauso das „man“.

- Nutzen Sie Schaubilder, Diagramme etc. soweit sinnvoll.

- Machen Sie keine Screenshots von R-Syntax, die Sie im Bericht wiedergeben. Stellen Sie die Syntax stattdessen in eine Datei, die Sie mit einreichen.



#### Redlichkeit: Machen Sie Ihre Ergebnisse nachvollziehbar

- Was sind Ihre eigenen Gedanken und welche Gedanken haben Sie übernommen – machen Sie dies kenntlich, indem Sie übernommen Gedanken als Zitate kennzeichnen.

- Es ist nicht schändlich, Gedanken anderer zu übernehmen. Im Gegenteil: „Auf den Schultern von Giganten“ ist eine Credo der Wissenschaft. Sie können also auch replizieren.

- Andere Wissenschaftlis sollte die Möglichkeit haben, Ihre Ergebnisse rekonstruieren zu können. Dazu zählt, dass Sie Ihre Recherchestrategie offen legen (welche Datenbanken etc.). Ebenso, dass Sie Ihr methodisches Vorgehen nachvollziehbar machen.

- Weisen Sie auf Schwächen (und Stärken) und sich nach Ihrer Arbeit anschließende Forschungsfragen hin, so dass andere auf Ihren Schultern weitersehen können.

- Explizieren Sie Ihre Suchstrategie für Literatur (welche Datenbanken? Welche Suchbegriffe? Wie viele Treffer? Welche ausgewählt? Nach welchen Kriterien?) Ausführliche Details in den Anhang packen.

- Reichen Sie Syntax, Daten und ggf. Stimulus-Materialien (elektronisch) ein.

- Versuchen Sie, den Nutzen Ihrer Arbeit für Dritte aufzuzeigen.


#### Leserseite: Schreiben Sie für den Leser


Hier sind einige typische Fragen, die sich Lesis - implizit oder explizit - stellen:

- *Worum geht's?* --> Aussagekräftige Titel, Zusammenfassungen, Kernaussagen, Schaubilder, Fazit ...
- *Was nützt es mir?* --> Sinn, Zweck, Ziel und Bedeutung in der Einleitung aufzeigen, Praxisnutzen herausstellen, ggf. Checklisten, Leitfäden etc. erstellen
- *Was soll ich jetzt tun?* --> Geben Sie Handlungsempfehlungen, ggf. „Kochrezepte“, wie in einer bestimmten Situation vorzugehen ist, z. B. Typologien beschreiben
- *So what?*  -->  Tja, und nun :-)



### Gutachtenerstellung


- Ein Teil des Gesamteindrucks der Arbeit spiegelt sich in den Kommentaren des Gutachters wider. Jedoch spiegelt die Summe der Kommentare nicht (zwangsläufig) die Gesamtnote wider, sondern nur denjenigen Teil, für den der Gutachter es für sinnvoll befunden hat, explizite Kommentare anzugeben.
- Es ist insbesondere nicht möglich, von der Anzahl der positiven oder negativen Kommentare auf eine bestimmte Note zurückzuschließen.
- Auch Vergleiche zwischen Gutachten verschiedener Student/innen ist nicht rein auf Basis der Kommentare möglich, da die Kommentare nur einen Ausschnitt des Meinungsbilds des Gutachters widerspiegeln.
- Die Kommentare des Gutachters verfolgen erstens den Zweck einer Rückmeldung zum Leistungsstand und zweitens Hilfestellung zur Verbesserung, damit der/die entsprechend Student/in den eigenen Leistungsstand verbessern kann.
- Weitere Hinweise zur Notengebung und Beurteilung sind auf der Modulseite bzw. den offiziellen Regularien und Hinweisen zu finden.
- Sollten Sie Fragen an den Gutachter stellen wollen zu Ihrem Gutachten, so melden Sie sich zur Sprechstunde an.






